// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: classifications/queries/classification/query_request.proto

package com.assetmantle.modules.classifications.queries.classification;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_classifications_queries_classification_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_classifications_queries_classification_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:classifications/queries/classification" +
      "/query_request.proto\022:assetmantle.module" +
      "s.classifications.queries.classification" +
      "\032\035classifications/key/key.proto\"N\n\014Query" +
      "Request\022>\n\003key\030\001 \001(\0132,.assetmantle.modul" +
      "es.classifications.key.KeyR\003keyB\252\003\n>com." +
      "assetmantle.modules.classifications.quer" +
      "ies.classificationB\021QueryRequestProtoP\001Z" +
      "Ggithub.com/AssetMantle/modules/x/classi" +
      "fications/queries/classification\242\002\005AMCQC" +
      "\252\002:Assetmantle.Modules.Classifications.Q" +
      "ueries.Classification\312\002:Assetmantle\\Modu" +
      "les\\Classifications\\Queries\\Classificati" +
      "on\342\002FAssetmantle\\Modules\\Classifications" +
      "\\Queries\\Classification\\GPBMetadata\352\002>As" +
      "setmantle::Modules::Classifications::Que" +
      "ries::Classificationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.modules.classifications.key.KeyProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_classifications_queries_classification_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_classifications_queries_classification_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_classifications_queries_classification_QueryRequest_descriptor,
        new java.lang.String[] { "Key", });
    com.assetmantle.modules.classifications.key.KeyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
