// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: classifications/queries/classification/query_response.proto

package com.assetmantle.modules.classifications.queries.classification;

public interface QueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assetmantle.modules.classifications.queries.classification.QueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.assetmantle.modules.classifications.record.Record record = 1 [json_name = "record"];</code>
   * @return Whether the record field is set.
   */
  boolean hasRecord();
  /**
   * <code>.assetmantle.modules.classifications.record.Record record = 1 [json_name = "record"];</code>
   * @return The record.
   */
  com.assetmantle.modules.classifications.record.Record getRecord();
  /**
   * <code>.assetmantle.modules.classifications.record.Record record = 1 [json_name = "record"];</code>
   */
  com.assetmantle.modules.classifications.record.RecordOrBuilder getRecordOrBuilder();
}
