// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/base/store/v1beta1/listening.proto

package com.cosmos.base.store.v1beta1;

/**
 * <pre>
 * BlockMetadata contains all the abci event data of a block
 * the file streamer dump them into files together with the state changes.
 * </pre>
 *
 * Protobuf type {@code cosmos.base.store.v1beta1.BlockMetadata}
 */
public final class BlockMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cosmos.base.store.v1beta1.BlockMetadata)
    BlockMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockMetadata.newBuilder() to construct.
  private BlockMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockMetadata() {
    deliverTxs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockMetadata();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cosmos.base.store.v1beta1.BlockMetadata.class, com.cosmos.base.store.v1beta1.BlockMetadata.Builder.class);
  }

  public interface DeliverTxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.base.store.v1beta1.BlockMetadata.DeliverTx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
     * @return The request.
     */
    com.tendermint.abci.RequestDeliverTx getRequest();
    /**
     * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
     */
    com.tendermint.abci.RequestDeliverTxOrBuilder getRequestOrBuilder();

    /**
     * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
     * @return The response.
     */
    com.tendermint.abci.ResponseDeliverTx getResponse();
    /**
     * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
     */
    com.tendermint.abci.ResponseDeliverTxOrBuilder getResponseOrBuilder();
  }
  /**
   * <pre>
   * DeliverTx encapulate deliver tx request and response.
   * </pre>
   *
   * Protobuf type {@code cosmos.base.store.v1beta1.BlockMetadata.DeliverTx}
   */
  public static final class DeliverTx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.base.store.v1beta1.BlockMetadata.DeliverTx)
      DeliverTxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeliverTx.newBuilder() to construct.
    private DeliverTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeliverTx() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeliverTx();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_DeliverTx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_DeliverTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.class, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.tendermint.abci.RequestDeliverTx request_;
    /**
     * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
     * @return The request.
     */
    @java.lang.Override
    public com.tendermint.abci.RequestDeliverTx getRequest() {
      return request_ == null ? com.tendermint.abci.RequestDeliverTx.getDefaultInstance() : request_;
    }
    /**
     * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
     */
    @java.lang.Override
    public com.tendermint.abci.RequestDeliverTxOrBuilder getRequestOrBuilder() {
      return request_ == null ? com.tendermint.abci.RequestDeliverTx.getDefaultInstance() : request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private com.tendermint.abci.ResponseDeliverTx response_;
    /**
     * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
     * @return The response.
     */
    @java.lang.Override
    public com.tendermint.abci.ResponseDeliverTx getResponse() {
      return response_ == null ? com.tendermint.abci.ResponseDeliverTx.getDefaultInstance() : response_;
    }
    /**
     * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
     */
    @java.lang.Override
    public com.tendermint.abci.ResponseDeliverTxOrBuilder getResponseOrBuilder() {
      return response_ == null ? com.tendermint.abci.ResponseDeliverTx.getDefaultInstance() : response_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (response_ != null) {
        output.writeMessage(2, getResponse());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx)) {
        return super.equals(obj);
      }
      com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx other = (com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * DeliverTx encapulate deliver tx request and response.
     * </pre>
     *
     * Protobuf type {@code cosmos.base.store.v1beta1.BlockMetadata.DeliverTx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.base.store.v1beta1.BlockMetadata.DeliverTx)
        com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_DeliverTx_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_DeliverTx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.class, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder.class);
      }

      // Construct using com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        response_ = null;
        if (responseBuilder_ != null) {
          responseBuilder_.dispose();
          responseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_DeliverTx_descriptor;
      }

      @java.lang.Override
      public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx getDefaultInstanceForType() {
        return com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.getDefaultInstance();
      }

      @java.lang.Override
      public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx build() {
        com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx buildPartial() {
        com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx result = new com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.request_ = requestBuilder_ == null
              ? request_
              : requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.response_ = responseBuilder_ == null
              ? response_
              : responseBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx) {
          return mergeFrom((com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx other) {
        if (other == com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getResponseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.tendermint.abci.RequestDeliverTx request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tendermint.abci.RequestDeliverTx, com.tendermint.abci.RequestDeliverTx.Builder, com.tendermint.abci.RequestDeliverTxOrBuilder> requestBuilder_;
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       * @return The request.
       */
      public com.tendermint.abci.RequestDeliverTx getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.tendermint.abci.RequestDeliverTx.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       */
      public Builder setRequest(com.tendermint.abci.RequestDeliverTx value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       */
      public Builder setRequest(
          com.tendermint.abci.RequestDeliverTx.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       */
      public Builder mergeRequest(com.tendermint.abci.RequestDeliverTx value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            request_ != null &&
            request_ != com.tendermint.abci.RequestDeliverTx.getDefaultInstance()) {
            getRequestBuilder().mergeFrom(value);
          } else {
            request_ = value;
          }
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000001);
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       */
      public com.tendermint.abci.RequestDeliverTx.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       */
      public com.tendermint.abci.RequestDeliverTxOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.tendermint.abci.RequestDeliverTx.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.tendermint.abci.RequestDeliverTx request = 1 [json_name = "request"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tendermint.abci.RequestDeliverTx, com.tendermint.abci.RequestDeliverTx.Builder, com.tendermint.abci.RequestDeliverTxOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tendermint.abci.RequestDeliverTx, com.tendermint.abci.RequestDeliverTx.Builder, com.tendermint.abci.RequestDeliverTxOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private com.tendermint.abci.ResponseDeliverTx response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tendermint.abci.ResponseDeliverTx, com.tendermint.abci.ResponseDeliverTx.Builder, com.tendermint.abci.ResponseDeliverTxOrBuilder> responseBuilder_;
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       * @return The response.
       */
      public com.tendermint.abci.ResponseDeliverTx getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.tendermint.abci.ResponseDeliverTx.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       */
      public Builder setResponse(com.tendermint.abci.ResponseDeliverTx value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       */
      public Builder setResponse(
          com.tendermint.abci.ResponseDeliverTx.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       */
      public Builder mergeResponse(com.tendermint.abci.ResponseDeliverTx value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            response_ != null &&
            response_ != com.tendermint.abci.ResponseDeliverTx.getDefaultInstance()) {
            getResponseBuilder().mergeFrom(value);
          } else {
            response_ = value;
          }
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = null;
        if (responseBuilder_ != null) {
          responseBuilder_.dispose();
          responseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       */
      public com.tendermint.abci.ResponseDeliverTx.Builder getResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       */
      public com.tendermint.abci.ResponseDeliverTxOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.tendermint.abci.ResponseDeliverTx.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.tendermint.abci.ResponseDeliverTx response = 2 [json_name = "response"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tendermint.abci.ResponseDeliverTx, com.tendermint.abci.ResponseDeliverTx.Builder, com.tendermint.abci.ResponseDeliverTxOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tendermint.abci.ResponseDeliverTx, com.tendermint.abci.ResponseDeliverTx.Builder, com.tendermint.abci.ResponseDeliverTxOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.base.store.v1beta1.BlockMetadata.DeliverTx)
    }

    // @@protoc_insertion_point(class_scope:cosmos.base.store.v1beta1.BlockMetadata.DeliverTx)
    private static final com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx();
    }

    public static com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeliverTx>
        PARSER = new com.google.protobuf.AbstractParser<DeliverTx>() {
      @java.lang.Override
      public DeliverTx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DeliverTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeliverTx> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int REQUEST_BEGIN_BLOCK_FIELD_NUMBER = 1;
  private com.tendermint.abci.RequestBeginBlock requestBeginBlock_;
  /**
   * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
   * @return Whether the requestBeginBlock field is set.
   */
  @java.lang.Override
  public boolean hasRequestBeginBlock() {
    return requestBeginBlock_ != null;
  }
  /**
   * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
   * @return The requestBeginBlock.
   */
  @java.lang.Override
  public com.tendermint.abci.RequestBeginBlock getRequestBeginBlock() {
    return requestBeginBlock_ == null ? com.tendermint.abci.RequestBeginBlock.getDefaultInstance() : requestBeginBlock_;
  }
  /**
   * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
   */
  @java.lang.Override
  public com.tendermint.abci.RequestBeginBlockOrBuilder getRequestBeginBlockOrBuilder() {
    return requestBeginBlock_ == null ? com.tendermint.abci.RequestBeginBlock.getDefaultInstance() : requestBeginBlock_;
  }

  public static final int RESPONSE_BEGIN_BLOCK_FIELD_NUMBER = 2;
  private com.tendermint.abci.ResponseBeginBlock responseBeginBlock_;
  /**
   * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
   * @return Whether the responseBeginBlock field is set.
   */
  @java.lang.Override
  public boolean hasResponseBeginBlock() {
    return responseBeginBlock_ != null;
  }
  /**
   * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
   * @return The responseBeginBlock.
   */
  @java.lang.Override
  public com.tendermint.abci.ResponseBeginBlock getResponseBeginBlock() {
    return responseBeginBlock_ == null ? com.tendermint.abci.ResponseBeginBlock.getDefaultInstance() : responseBeginBlock_;
  }
  /**
   * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
   */
  @java.lang.Override
  public com.tendermint.abci.ResponseBeginBlockOrBuilder getResponseBeginBlockOrBuilder() {
    return responseBeginBlock_ == null ? com.tendermint.abci.ResponseBeginBlock.getDefaultInstance() : responseBeginBlock_;
  }

  public static final int DELIVER_TXS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx> deliverTxs_;
  /**
   * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx> getDeliverTxsList() {
    return deliverTxs_;
  }
  /**
   * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder> 
      getDeliverTxsOrBuilderList() {
    return deliverTxs_;
  }
  /**
   * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
   */
  @java.lang.Override
  public int getDeliverTxsCount() {
    return deliverTxs_.size();
  }
  /**
   * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
   */
  @java.lang.Override
  public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx getDeliverTxs(int index) {
    return deliverTxs_.get(index);
  }
  /**
   * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
   */
  @java.lang.Override
  public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder getDeliverTxsOrBuilder(
      int index) {
    return deliverTxs_.get(index);
  }

  public static final int REQUEST_END_BLOCK_FIELD_NUMBER = 4;
  private com.tendermint.abci.RequestEndBlock requestEndBlock_;
  /**
   * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
   * @return Whether the requestEndBlock field is set.
   */
  @java.lang.Override
  public boolean hasRequestEndBlock() {
    return requestEndBlock_ != null;
  }
  /**
   * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
   * @return The requestEndBlock.
   */
  @java.lang.Override
  public com.tendermint.abci.RequestEndBlock getRequestEndBlock() {
    return requestEndBlock_ == null ? com.tendermint.abci.RequestEndBlock.getDefaultInstance() : requestEndBlock_;
  }
  /**
   * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
   */
  @java.lang.Override
  public com.tendermint.abci.RequestEndBlockOrBuilder getRequestEndBlockOrBuilder() {
    return requestEndBlock_ == null ? com.tendermint.abci.RequestEndBlock.getDefaultInstance() : requestEndBlock_;
  }

  public static final int RESPONSE_END_BLOCK_FIELD_NUMBER = 5;
  private com.tendermint.abci.ResponseEndBlock responseEndBlock_;
  /**
   * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
   * @return Whether the responseEndBlock field is set.
   */
  @java.lang.Override
  public boolean hasResponseEndBlock() {
    return responseEndBlock_ != null;
  }
  /**
   * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
   * @return The responseEndBlock.
   */
  @java.lang.Override
  public com.tendermint.abci.ResponseEndBlock getResponseEndBlock() {
    return responseEndBlock_ == null ? com.tendermint.abci.ResponseEndBlock.getDefaultInstance() : responseEndBlock_;
  }
  /**
   * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
   */
  @java.lang.Override
  public com.tendermint.abci.ResponseEndBlockOrBuilder getResponseEndBlockOrBuilder() {
    return responseEndBlock_ == null ? com.tendermint.abci.ResponseEndBlock.getDefaultInstance() : responseEndBlock_;
  }

  public static final int RESPONSE_COMMIT_FIELD_NUMBER = 6;
  private com.tendermint.abci.ResponseCommit responseCommit_;
  /**
   * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
   * @return Whether the responseCommit field is set.
   */
  @java.lang.Override
  public boolean hasResponseCommit() {
    return responseCommit_ != null;
  }
  /**
   * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
   * @return The responseCommit.
   */
  @java.lang.Override
  public com.tendermint.abci.ResponseCommit getResponseCommit() {
    return responseCommit_ == null ? com.tendermint.abci.ResponseCommit.getDefaultInstance() : responseCommit_;
  }
  /**
   * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
   */
  @java.lang.Override
  public com.tendermint.abci.ResponseCommitOrBuilder getResponseCommitOrBuilder() {
    return responseCommit_ == null ? com.tendermint.abci.ResponseCommit.getDefaultInstance() : responseCommit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestBeginBlock_ != null) {
      output.writeMessage(1, getRequestBeginBlock());
    }
    if (responseBeginBlock_ != null) {
      output.writeMessage(2, getResponseBeginBlock());
    }
    for (int i = 0; i < deliverTxs_.size(); i++) {
      output.writeMessage(3, deliverTxs_.get(i));
    }
    if (requestEndBlock_ != null) {
      output.writeMessage(4, getRequestEndBlock());
    }
    if (responseEndBlock_ != null) {
      output.writeMessage(5, getResponseEndBlock());
    }
    if (responseCommit_ != null) {
      output.writeMessage(6, getResponseCommit());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestBeginBlock_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRequestBeginBlock());
    }
    if (responseBeginBlock_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResponseBeginBlock());
    }
    for (int i = 0; i < deliverTxs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, deliverTxs_.get(i));
    }
    if (requestEndBlock_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRequestEndBlock());
    }
    if (responseEndBlock_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getResponseEndBlock());
    }
    if (responseCommit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getResponseCommit());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cosmos.base.store.v1beta1.BlockMetadata)) {
      return super.equals(obj);
    }
    com.cosmos.base.store.v1beta1.BlockMetadata other = (com.cosmos.base.store.v1beta1.BlockMetadata) obj;

    if (hasRequestBeginBlock() != other.hasRequestBeginBlock()) return false;
    if (hasRequestBeginBlock()) {
      if (!getRequestBeginBlock()
          .equals(other.getRequestBeginBlock())) return false;
    }
    if (hasResponseBeginBlock() != other.hasResponseBeginBlock()) return false;
    if (hasResponseBeginBlock()) {
      if (!getResponseBeginBlock()
          .equals(other.getResponseBeginBlock())) return false;
    }
    if (!getDeliverTxsList()
        .equals(other.getDeliverTxsList())) return false;
    if (hasRequestEndBlock() != other.hasRequestEndBlock()) return false;
    if (hasRequestEndBlock()) {
      if (!getRequestEndBlock()
          .equals(other.getRequestEndBlock())) return false;
    }
    if (hasResponseEndBlock() != other.hasResponseEndBlock()) return false;
    if (hasResponseEndBlock()) {
      if (!getResponseEndBlock()
          .equals(other.getResponseEndBlock())) return false;
    }
    if (hasResponseCommit() != other.hasResponseCommit()) return false;
    if (hasResponseCommit()) {
      if (!getResponseCommit()
          .equals(other.getResponseCommit())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestBeginBlock()) {
      hash = (37 * hash) + REQUEST_BEGIN_BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getRequestBeginBlock().hashCode();
    }
    if (hasResponseBeginBlock()) {
      hash = (37 * hash) + RESPONSE_BEGIN_BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getResponseBeginBlock().hashCode();
    }
    if (getDeliverTxsCount() > 0) {
      hash = (37 * hash) + DELIVER_TXS_FIELD_NUMBER;
      hash = (53 * hash) + getDeliverTxsList().hashCode();
    }
    if (hasRequestEndBlock()) {
      hash = (37 * hash) + REQUEST_END_BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getRequestEndBlock().hashCode();
    }
    if (hasResponseEndBlock()) {
      hash = (37 * hash) + RESPONSE_END_BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getResponseEndBlock().hashCode();
    }
    if (hasResponseCommit()) {
      hash = (37 * hash) + RESPONSE_COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCommit().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cosmos.base.store.v1beta1.BlockMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cosmos.base.store.v1beta1.BlockMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * BlockMetadata contains all the abci event data of a block
   * the file streamer dump them into files together with the state changes.
   * </pre>
   *
   * Protobuf type {@code cosmos.base.store.v1beta1.BlockMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cosmos.base.store.v1beta1.BlockMetadata)
      com.cosmos.base.store.v1beta1.BlockMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cosmos.base.store.v1beta1.BlockMetadata.class, com.cosmos.base.store.v1beta1.BlockMetadata.Builder.class);
    }

    // Construct using com.cosmos.base.store.v1beta1.BlockMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestBeginBlock_ = null;
      if (requestBeginBlockBuilder_ != null) {
        requestBeginBlockBuilder_.dispose();
        requestBeginBlockBuilder_ = null;
      }
      responseBeginBlock_ = null;
      if (responseBeginBlockBuilder_ != null) {
        responseBeginBlockBuilder_.dispose();
        responseBeginBlockBuilder_ = null;
      }
      if (deliverTxsBuilder_ == null) {
        deliverTxs_ = java.util.Collections.emptyList();
      } else {
        deliverTxs_ = null;
        deliverTxsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      requestEndBlock_ = null;
      if (requestEndBlockBuilder_ != null) {
        requestEndBlockBuilder_.dispose();
        requestEndBlockBuilder_ = null;
      }
      responseEndBlock_ = null;
      if (responseEndBlockBuilder_ != null) {
        responseEndBlockBuilder_.dispose();
        responseEndBlockBuilder_ = null;
      }
      responseCommit_ = null;
      if (responseCommitBuilder_ != null) {
        responseCommitBuilder_.dispose();
        responseCommitBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cosmos.base.store.v1beta1.ListeningProto.internal_static_cosmos_base_store_v1beta1_BlockMetadata_descriptor;
    }

    @java.lang.Override
    public com.cosmos.base.store.v1beta1.BlockMetadata getDefaultInstanceForType() {
      return com.cosmos.base.store.v1beta1.BlockMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.cosmos.base.store.v1beta1.BlockMetadata build() {
      com.cosmos.base.store.v1beta1.BlockMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cosmos.base.store.v1beta1.BlockMetadata buildPartial() {
      com.cosmos.base.store.v1beta1.BlockMetadata result = new com.cosmos.base.store.v1beta1.BlockMetadata(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.cosmos.base.store.v1beta1.BlockMetadata result) {
      if (deliverTxsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          deliverTxs_ = java.util.Collections.unmodifiableList(deliverTxs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.deliverTxs_ = deliverTxs_;
      } else {
        result.deliverTxs_ = deliverTxsBuilder_.build();
      }
    }

    private void buildPartial0(com.cosmos.base.store.v1beta1.BlockMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestBeginBlock_ = requestBeginBlockBuilder_ == null
            ? requestBeginBlock_
            : requestBeginBlockBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.responseBeginBlock_ = responseBeginBlockBuilder_ == null
            ? responseBeginBlock_
            : responseBeginBlockBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.requestEndBlock_ = requestEndBlockBuilder_ == null
            ? requestEndBlock_
            : requestEndBlockBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.responseEndBlock_ = responseEndBlockBuilder_ == null
            ? responseEndBlock_
            : responseEndBlockBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.responseCommit_ = responseCommitBuilder_ == null
            ? responseCommit_
            : responseCommitBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cosmos.base.store.v1beta1.BlockMetadata) {
        return mergeFrom((com.cosmos.base.store.v1beta1.BlockMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cosmos.base.store.v1beta1.BlockMetadata other) {
      if (other == com.cosmos.base.store.v1beta1.BlockMetadata.getDefaultInstance()) return this;
      if (other.hasRequestBeginBlock()) {
        mergeRequestBeginBlock(other.getRequestBeginBlock());
      }
      if (other.hasResponseBeginBlock()) {
        mergeResponseBeginBlock(other.getResponseBeginBlock());
      }
      if (deliverTxsBuilder_ == null) {
        if (!other.deliverTxs_.isEmpty()) {
          if (deliverTxs_.isEmpty()) {
            deliverTxs_ = other.deliverTxs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDeliverTxsIsMutable();
            deliverTxs_.addAll(other.deliverTxs_);
          }
          onChanged();
        }
      } else {
        if (!other.deliverTxs_.isEmpty()) {
          if (deliverTxsBuilder_.isEmpty()) {
            deliverTxsBuilder_.dispose();
            deliverTxsBuilder_ = null;
            deliverTxs_ = other.deliverTxs_;
            bitField0_ = (bitField0_ & ~0x00000004);
            deliverTxsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDeliverTxsFieldBuilder() : null;
          } else {
            deliverTxsBuilder_.addAllMessages(other.deliverTxs_);
          }
        }
      }
      if (other.hasRequestEndBlock()) {
        mergeRequestEndBlock(other.getRequestEndBlock());
      }
      if (other.hasResponseEndBlock()) {
        mergeResponseEndBlock(other.getResponseEndBlock());
      }
      if (other.hasResponseCommit()) {
        mergeResponseCommit(other.getResponseCommit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRequestBeginBlockFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getResponseBeginBlockFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx m =
                  input.readMessage(
                      com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.parser(),
                      extensionRegistry);
              if (deliverTxsBuilder_ == null) {
                ensureDeliverTxsIsMutable();
                deliverTxs_.add(m);
              } else {
                deliverTxsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getRequestEndBlockFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getResponseEndBlockFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getResponseCommitFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.tendermint.abci.RequestBeginBlock requestBeginBlock_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.RequestBeginBlock, com.tendermint.abci.RequestBeginBlock.Builder, com.tendermint.abci.RequestBeginBlockOrBuilder> requestBeginBlockBuilder_;
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     * @return Whether the requestBeginBlock field is set.
     */
    public boolean hasRequestBeginBlock() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     * @return The requestBeginBlock.
     */
    public com.tendermint.abci.RequestBeginBlock getRequestBeginBlock() {
      if (requestBeginBlockBuilder_ == null) {
        return requestBeginBlock_ == null ? com.tendermint.abci.RequestBeginBlock.getDefaultInstance() : requestBeginBlock_;
      } else {
        return requestBeginBlockBuilder_.getMessage();
      }
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     */
    public Builder setRequestBeginBlock(com.tendermint.abci.RequestBeginBlock value) {
      if (requestBeginBlockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestBeginBlock_ = value;
      } else {
        requestBeginBlockBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     */
    public Builder setRequestBeginBlock(
        com.tendermint.abci.RequestBeginBlock.Builder builderForValue) {
      if (requestBeginBlockBuilder_ == null) {
        requestBeginBlock_ = builderForValue.build();
      } else {
        requestBeginBlockBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     */
    public Builder mergeRequestBeginBlock(com.tendermint.abci.RequestBeginBlock value) {
      if (requestBeginBlockBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          requestBeginBlock_ != null &&
          requestBeginBlock_ != com.tendermint.abci.RequestBeginBlock.getDefaultInstance()) {
          getRequestBeginBlockBuilder().mergeFrom(value);
        } else {
          requestBeginBlock_ = value;
        }
      } else {
        requestBeginBlockBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     */
    public Builder clearRequestBeginBlock() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestBeginBlock_ = null;
      if (requestBeginBlockBuilder_ != null) {
        requestBeginBlockBuilder_.dispose();
        requestBeginBlockBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     */
    public com.tendermint.abci.RequestBeginBlock.Builder getRequestBeginBlockBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRequestBeginBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     */
    public com.tendermint.abci.RequestBeginBlockOrBuilder getRequestBeginBlockOrBuilder() {
      if (requestBeginBlockBuilder_ != null) {
        return requestBeginBlockBuilder_.getMessageOrBuilder();
      } else {
        return requestBeginBlock_ == null ?
            com.tendermint.abci.RequestBeginBlock.getDefaultInstance() : requestBeginBlock_;
      }
    }
    /**
     * <code>.tendermint.abci.RequestBeginBlock request_begin_block = 1 [json_name = "requestBeginBlock"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.RequestBeginBlock, com.tendermint.abci.RequestBeginBlock.Builder, com.tendermint.abci.RequestBeginBlockOrBuilder> 
        getRequestBeginBlockFieldBuilder() {
      if (requestBeginBlockBuilder_ == null) {
        requestBeginBlockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tendermint.abci.RequestBeginBlock, com.tendermint.abci.RequestBeginBlock.Builder, com.tendermint.abci.RequestBeginBlockOrBuilder>(
                getRequestBeginBlock(),
                getParentForChildren(),
                isClean());
        requestBeginBlock_ = null;
      }
      return requestBeginBlockBuilder_;
    }

    private com.tendermint.abci.ResponseBeginBlock responseBeginBlock_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.ResponseBeginBlock, com.tendermint.abci.ResponseBeginBlock.Builder, com.tendermint.abci.ResponseBeginBlockOrBuilder> responseBeginBlockBuilder_;
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     * @return Whether the responseBeginBlock field is set.
     */
    public boolean hasResponseBeginBlock() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     * @return The responseBeginBlock.
     */
    public com.tendermint.abci.ResponseBeginBlock getResponseBeginBlock() {
      if (responseBeginBlockBuilder_ == null) {
        return responseBeginBlock_ == null ? com.tendermint.abci.ResponseBeginBlock.getDefaultInstance() : responseBeginBlock_;
      } else {
        return responseBeginBlockBuilder_.getMessage();
      }
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     */
    public Builder setResponseBeginBlock(com.tendermint.abci.ResponseBeginBlock value) {
      if (responseBeginBlockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responseBeginBlock_ = value;
      } else {
        responseBeginBlockBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     */
    public Builder setResponseBeginBlock(
        com.tendermint.abci.ResponseBeginBlock.Builder builderForValue) {
      if (responseBeginBlockBuilder_ == null) {
        responseBeginBlock_ = builderForValue.build();
      } else {
        responseBeginBlockBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     */
    public Builder mergeResponseBeginBlock(com.tendermint.abci.ResponseBeginBlock value) {
      if (responseBeginBlockBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          responseBeginBlock_ != null &&
          responseBeginBlock_ != com.tendermint.abci.ResponseBeginBlock.getDefaultInstance()) {
          getResponseBeginBlockBuilder().mergeFrom(value);
        } else {
          responseBeginBlock_ = value;
        }
      } else {
        responseBeginBlockBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     */
    public Builder clearResponseBeginBlock() {
      bitField0_ = (bitField0_ & ~0x00000002);
      responseBeginBlock_ = null;
      if (responseBeginBlockBuilder_ != null) {
        responseBeginBlockBuilder_.dispose();
        responseBeginBlockBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     */
    public com.tendermint.abci.ResponseBeginBlock.Builder getResponseBeginBlockBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getResponseBeginBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     */
    public com.tendermint.abci.ResponseBeginBlockOrBuilder getResponseBeginBlockOrBuilder() {
      if (responseBeginBlockBuilder_ != null) {
        return responseBeginBlockBuilder_.getMessageOrBuilder();
      } else {
        return responseBeginBlock_ == null ?
            com.tendermint.abci.ResponseBeginBlock.getDefaultInstance() : responseBeginBlock_;
      }
    }
    /**
     * <code>.tendermint.abci.ResponseBeginBlock response_begin_block = 2 [json_name = "responseBeginBlock"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.ResponseBeginBlock, com.tendermint.abci.ResponseBeginBlock.Builder, com.tendermint.abci.ResponseBeginBlockOrBuilder> 
        getResponseBeginBlockFieldBuilder() {
      if (responseBeginBlockBuilder_ == null) {
        responseBeginBlockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tendermint.abci.ResponseBeginBlock, com.tendermint.abci.ResponseBeginBlock.Builder, com.tendermint.abci.ResponseBeginBlockOrBuilder>(
                getResponseBeginBlock(),
                getParentForChildren(),
                isClean());
        responseBeginBlock_ = null;
      }
      return responseBeginBlockBuilder_;
    }

    private java.util.List<com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx> deliverTxs_ =
      java.util.Collections.emptyList();
    private void ensureDeliverTxsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        deliverTxs_ = new java.util.ArrayList<com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx>(deliverTxs_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder> deliverTxsBuilder_;

    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public java.util.List<com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx> getDeliverTxsList() {
      if (deliverTxsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deliverTxs_);
      } else {
        return deliverTxsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public int getDeliverTxsCount() {
      if (deliverTxsBuilder_ == null) {
        return deliverTxs_.size();
      } else {
        return deliverTxsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx getDeliverTxs(int index) {
      if (deliverTxsBuilder_ == null) {
        return deliverTxs_.get(index);
      } else {
        return deliverTxsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder setDeliverTxs(
        int index, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx value) {
      if (deliverTxsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliverTxsIsMutable();
        deliverTxs_.set(index, value);
        onChanged();
      } else {
        deliverTxsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder setDeliverTxs(
        int index, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder builderForValue) {
      if (deliverTxsBuilder_ == null) {
        ensureDeliverTxsIsMutable();
        deliverTxs_.set(index, builderForValue.build());
        onChanged();
      } else {
        deliverTxsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder addDeliverTxs(com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx value) {
      if (deliverTxsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliverTxsIsMutable();
        deliverTxs_.add(value);
        onChanged();
      } else {
        deliverTxsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder addDeliverTxs(
        int index, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx value) {
      if (deliverTxsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliverTxsIsMutable();
        deliverTxs_.add(index, value);
        onChanged();
      } else {
        deliverTxsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder addDeliverTxs(
        com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder builderForValue) {
      if (deliverTxsBuilder_ == null) {
        ensureDeliverTxsIsMutable();
        deliverTxs_.add(builderForValue.build());
        onChanged();
      } else {
        deliverTxsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder addDeliverTxs(
        int index, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder builderForValue) {
      if (deliverTxsBuilder_ == null) {
        ensureDeliverTxsIsMutable();
        deliverTxs_.add(index, builderForValue.build());
        onChanged();
      } else {
        deliverTxsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder addAllDeliverTxs(
        java.lang.Iterable<? extends com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx> values) {
      if (deliverTxsBuilder_ == null) {
        ensureDeliverTxsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deliverTxs_);
        onChanged();
      } else {
        deliverTxsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder clearDeliverTxs() {
      if (deliverTxsBuilder_ == null) {
        deliverTxs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        deliverTxsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public Builder removeDeliverTxs(int index) {
      if (deliverTxsBuilder_ == null) {
        ensureDeliverTxsIsMutable();
        deliverTxs_.remove(index);
        onChanged();
      } else {
        deliverTxsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder getDeliverTxsBuilder(
        int index) {
      return getDeliverTxsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder getDeliverTxsOrBuilder(
        int index) {
      if (deliverTxsBuilder_ == null) {
        return deliverTxs_.get(index);  } else {
        return deliverTxsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public java.util.List<? extends com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder> 
         getDeliverTxsOrBuilderList() {
      if (deliverTxsBuilder_ != null) {
        return deliverTxsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deliverTxs_);
      }
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder addDeliverTxsBuilder() {
      return getDeliverTxsFieldBuilder().addBuilder(
          com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.getDefaultInstance());
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder addDeliverTxsBuilder(
        int index) {
      return getDeliverTxsFieldBuilder().addBuilder(
          index, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.getDefaultInstance());
    }
    /**
     * <code>repeated .cosmos.base.store.v1beta1.BlockMetadata.DeliverTx deliver_txs = 3 [json_name = "deliverTxs"];</code>
     */
    public java.util.List<com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder> 
         getDeliverTxsBuilderList() {
      return getDeliverTxsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder> 
        getDeliverTxsFieldBuilder() {
      if (deliverTxsBuilder_ == null) {
        deliverTxsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTx.Builder, com.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxOrBuilder>(
                deliverTxs_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        deliverTxs_ = null;
      }
      return deliverTxsBuilder_;
    }

    private com.tendermint.abci.RequestEndBlock requestEndBlock_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.RequestEndBlock, com.tendermint.abci.RequestEndBlock.Builder, com.tendermint.abci.RequestEndBlockOrBuilder> requestEndBlockBuilder_;
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     * @return Whether the requestEndBlock field is set.
     */
    public boolean hasRequestEndBlock() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     * @return The requestEndBlock.
     */
    public com.tendermint.abci.RequestEndBlock getRequestEndBlock() {
      if (requestEndBlockBuilder_ == null) {
        return requestEndBlock_ == null ? com.tendermint.abci.RequestEndBlock.getDefaultInstance() : requestEndBlock_;
      } else {
        return requestEndBlockBuilder_.getMessage();
      }
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     */
    public Builder setRequestEndBlock(com.tendermint.abci.RequestEndBlock value) {
      if (requestEndBlockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestEndBlock_ = value;
      } else {
        requestEndBlockBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     */
    public Builder setRequestEndBlock(
        com.tendermint.abci.RequestEndBlock.Builder builderForValue) {
      if (requestEndBlockBuilder_ == null) {
        requestEndBlock_ = builderForValue.build();
      } else {
        requestEndBlockBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     */
    public Builder mergeRequestEndBlock(com.tendermint.abci.RequestEndBlock value) {
      if (requestEndBlockBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          requestEndBlock_ != null &&
          requestEndBlock_ != com.tendermint.abci.RequestEndBlock.getDefaultInstance()) {
          getRequestEndBlockBuilder().mergeFrom(value);
        } else {
          requestEndBlock_ = value;
        }
      } else {
        requestEndBlockBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     */
    public Builder clearRequestEndBlock() {
      bitField0_ = (bitField0_ & ~0x00000008);
      requestEndBlock_ = null;
      if (requestEndBlockBuilder_ != null) {
        requestEndBlockBuilder_.dispose();
        requestEndBlockBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     */
    public com.tendermint.abci.RequestEndBlock.Builder getRequestEndBlockBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getRequestEndBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     */
    public com.tendermint.abci.RequestEndBlockOrBuilder getRequestEndBlockOrBuilder() {
      if (requestEndBlockBuilder_ != null) {
        return requestEndBlockBuilder_.getMessageOrBuilder();
      } else {
        return requestEndBlock_ == null ?
            com.tendermint.abci.RequestEndBlock.getDefaultInstance() : requestEndBlock_;
      }
    }
    /**
     * <code>.tendermint.abci.RequestEndBlock request_end_block = 4 [json_name = "requestEndBlock"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.RequestEndBlock, com.tendermint.abci.RequestEndBlock.Builder, com.tendermint.abci.RequestEndBlockOrBuilder> 
        getRequestEndBlockFieldBuilder() {
      if (requestEndBlockBuilder_ == null) {
        requestEndBlockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tendermint.abci.RequestEndBlock, com.tendermint.abci.RequestEndBlock.Builder, com.tendermint.abci.RequestEndBlockOrBuilder>(
                getRequestEndBlock(),
                getParentForChildren(),
                isClean());
        requestEndBlock_ = null;
      }
      return requestEndBlockBuilder_;
    }

    private com.tendermint.abci.ResponseEndBlock responseEndBlock_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.ResponseEndBlock, com.tendermint.abci.ResponseEndBlock.Builder, com.tendermint.abci.ResponseEndBlockOrBuilder> responseEndBlockBuilder_;
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     * @return Whether the responseEndBlock field is set.
     */
    public boolean hasResponseEndBlock() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     * @return The responseEndBlock.
     */
    public com.tendermint.abci.ResponseEndBlock getResponseEndBlock() {
      if (responseEndBlockBuilder_ == null) {
        return responseEndBlock_ == null ? com.tendermint.abci.ResponseEndBlock.getDefaultInstance() : responseEndBlock_;
      } else {
        return responseEndBlockBuilder_.getMessage();
      }
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     */
    public Builder setResponseEndBlock(com.tendermint.abci.ResponseEndBlock value) {
      if (responseEndBlockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responseEndBlock_ = value;
      } else {
        responseEndBlockBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     */
    public Builder setResponseEndBlock(
        com.tendermint.abci.ResponseEndBlock.Builder builderForValue) {
      if (responseEndBlockBuilder_ == null) {
        responseEndBlock_ = builderForValue.build();
      } else {
        responseEndBlockBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     */
    public Builder mergeResponseEndBlock(com.tendermint.abci.ResponseEndBlock value) {
      if (responseEndBlockBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          responseEndBlock_ != null &&
          responseEndBlock_ != com.tendermint.abci.ResponseEndBlock.getDefaultInstance()) {
          getResponseEndBlockBuilder().mergeFrom(value);
        } else {
          responseEndBlock_ = value;
        }
      } else {
        responseEndBlockBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     */
    public Builder clearResponseEndBlock() {
      bitField0_ = (bitField0_ & ~0x00000010);
      responseEndBlock_ = null;
      if (responseEndBlockBuilder_ != null) {
        responseEndBlockBuilder_.dispose();
        responseEndBlockBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     */
    public com.tendermint.abci.ResponseEndBlock.Builder getResponseEndBlockBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getResponseEndBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     */
    public com.tendermint.abci.ResponseEndBlockOrBuilder getResponseEndBlockOrBuilder() {
      if (responseEndBlockBuilder_ != null) {
        return responseEndBlockBuilder_.getMessageOrBuilder();
      } else {
        return responseEndBlock_ == null ?
            com.tendermint.abci.ResponseEndBlock.getDefaultInstance() : responseEndBlock_;
      }
    }
    /**
     * <code>.tendermint.abci.ResponseEndBlock response_end_block = 5 [json_name = "responseEndBlock"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.ResponseEndBlock, com.tendermint.abci.ResponseEndBlock.Builder, com.tendermint.abci.ResponseEndBlockOrBuilder> 
        getResponseEndBlockFieldBuilder() {
      if (responseEndBlockBuilder_ == null) {
        responseEndBlockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tendermint.abci.ResponseEndBlock, com.tendermint.abci.ResponseEndBlock.Builder, com.tendermint.abci.ResponseEndBlockOrBuilder>(
                getResponseEndBlock(),
                getParentForChildren(),
                isClean());
        responseEndBlock_ = null;
      }
      return responseEndBlockBuilder_;
    }

    private com.tendermint.abci.ResponseCommit responseCommit_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.ResponseCommit, com.tendermint.abci.ResponseCommit.Builder, com.tendermint.abci.ResponseCommitOrBuilder> responseCommitBuilder_;
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     * @return Whether the responseCommit field is set.
     */
    public boolean hasResponseCommit() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     * @return The responseCommit.
     */
    public com.tendermint.abci.ResponseCommit getResponseCommit() {
      if (responseCommitBuilder_ == null) {
        return responseCommit_ == null ? com.tendermint.abci.ResponseCommit.getDefaultInstance() : responseCommit_;
      } else {
        return responseCommitBuilder_.getMessage();
      }
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     */
    public Builder setResponseCommit(com.tendermint.abci.ResponseCommit value) {
      if (responseCommitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responseCommit_ = value;
      } else {
        responseCommitBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     */
    public Builder setResponseCommit(
        com.tendermint.abci.ResponseCommit.Builder builderForValue) {
      if (responseCommitBuilder_ == null) {
        responseCommit_ = builderForValue.build();
      } else {
        responseCommitBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     */
    public Builder mergeResponseCommit(com.tendermint.abci.ResponseCommit value) {
      if (responseCommitBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          responseCommit_ != null &&
          responseCommit_ != com.tendermint.abci.ResponseCommit.getDefaultInstance()) {
          getResponseCommitBuilder().mergeFrom(value);
        } else {
          responseCommit_ = value;
        }
      } else {
        responseCommitBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     */
    public Builder clearResponseCommit() {
      bitField0_ = (bitField0_ & ~0x00000020);
      responseCommit_ = null;
      if (responseCommitBuilder_ != null) {
        responseCommitBuilder_.dispose();
        responseCommitBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     */
    public com.tendermint.abci.ResponseCommit.Builder getResponseCommitBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getResponseCommitFieldBuilder().getBuilder();
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     */
    public com.tendermint.abci.ResponseCommitOrBuilder getResponseCommitOrBuilder() {
      if (responseCommitBuilder_ != null) {
        return responseCommitBuilder_.getMessageOrBuilder();
      } else {
        return responseCommit_ == null ?
            com.tendermint.abci.ResponseCommit.getDefaultInstance() : responseCommit_;
      }
    }
    /**
     * <code>.tendermint.abci.ResponseCommit response_commit = 6 [json_name = "responseCommit"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tendermint.abci.ResponseCommit, com.tendermint.abci.ResponseCommit.Builder, com.tendermint.abci.ResponseCommitOrBuilder> 
        getResponseCommitFieldBuilder() {
      if (responseCommitBuilder_ == null) {
        responseCommitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tendermint.abci.ResponseCommit, com.tendermint.abci.ResponseCommit.Builder, com.tendermint.abci.ResponseCommitOrBuilder>(
                getResponseCommit(),
                getParentForChildren(),
                isClean());
        responseCommit_ = null;
      }
      return responseCommitBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cosmos.base.store.v1beta1.BlockMetadata)
  }

  // @@protoc_insertion_point(class_scope:cosmos.base.store.v1beta1.BlockMetadata)
  private static final com.cosmos.base.store.v1beta1.BlockMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cosmos.base.store.v1beta1.BlockMetadata();
  }

  public static com.cosmos.base.store.v1beta1.BlockMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockMetadata>
      PARSER = new com.google.protobuf.AbstractParser<BlockMetadata>() {
    @java.lang.Override
    public BlockMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cosmos.base.store.v1beta1.BlockMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

