// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/rpc/grpc/types.proto

package com.tendermint.rpc.grpc;

public interface ResponsePingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.rpc.grpc.ResponsePing)
    com.google.protobuf.MessageOrBuilder {
}
