// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/blockchain/types.proto

package com.tendermint.blockchain;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.blockchain.StatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
