// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/base/kv/v1beta1/kv.proto

package com.cosmos.base.kv.v1beta1;

public interface PairsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cosmos.base.kv.v1beta1.Pairs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cosmos.base.kv.v1beta1.Pair pairs = 1 [json_name = "pairs", (.gogoproto.nullable) = false];</code>
   */
  java.util.List<com.cosmos.base.kv.v1beta1.Pair> 
      getPairsList();
  /**
   * <code>repeated .cosmos.base.kv.v1beta1.Pair pairs = 1 [json_name = "pairs", (.gogoproto.nullable) = false];</code>
   */
  com.cosmos.base.kv.v1beta1.Pair getPairs(int index);
  /**
   * <code>repeated .cosmos.base.kv.v1beta1.Pair pairs = 1 [json_name = "pairs", (.gogoproto.nullable) = false];</code>
   */
  int getPairsCount();
  /**
   * <code>repeated .cosmos.base.kv.v1beta1.Pair pairs = 1 [json_name = "pairs", (.gogoproto.nullable) = false];</code>
   */
  java.util.List<? extends com.cosmos.base.kv.v1beta1.PairOrBuilder> 
      getPairsOrBuilderList();
  /**
   * <code>repeated .cosmos.base.kv.v1beta1.Pair pairs = 1 [json_name = "pairs", (.gogoproto.nullable) = false];</code>
   */
  com.cosmos.base.kv.v1beta1.PairOrBuilder getPairsOrBuilder(
      int index);
}
