// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/base/abci/v1beta1/abci.proto

package com.cosmos.base.abci.v1beta1;

/**
 * <pre>
 * TxMsgData defines a list of MsgData. A transaction will have a MsgData object
 * for each message.
 * </pre>
 *
 * Protobuf type {@code cosmos.base.abci.v1beta1.TxMsgData}
 */
public final class TxMsgData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cosmos.base.abci.v1beta1.TxMsgData)
    TxMsgDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TxMsgData.newBuilder() to construct.
  private TxMsgData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TxMsgData() {
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TxMsgData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cosmos.base.abci.v1beta1.AbciProto.internal_static_cosmos_base_abci_v1beta1_TxMsgData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cosmos.base.abci.v1beta1.AbciProto.internal_static_cosmos_base_abci_v1beta1_TxMsgData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cosmos.base.abci.v1beta1.TxMsgData.class, com.cosmos.base.abci.v1beta1.TxMsgData.Builder.class);
  }

  public static final int DATA_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.cosmos.base.abci.v1beta1.MsgData> data_;
  /**
   * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
   */
  @java.lang.Override
  public java.util.List<com.cosmos.base.abci.v1beta1.MsgData> getDataList() {
    return data_;
  }
  /**
   * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cosmos.base.abci.v1beta1.MsgDataOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
   */
  @java.lang.Override
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.cosmos.base.abci.v1beta1.MsgData getData(int index) {
    return data_.get(index);
  }
  /**
   * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.cosmos.base.abci.v1beta1.MsgDataOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(1, data_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, data_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cosmos.base.abci.v1beta1.TxMsgData)) {
      return super.equals(obj);
    }
    com.cosmos.base.abci.v1beta1.TxMsgData other = (com.cosmos.base.abci.v1beta1.TxMsgData) obj;

    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cosmos.base.abci.v1beta1.TxMsgData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cosmos.base.abci.v1beta1.TxMsgData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TxMsgData defines a list of MsgData. A transaction will have a MsgData object
   * for each message.
   * </pre>
   *
   * Protobuf type {@code cosmos.base.abci.v1beta1.TxMsgData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cosmos.base.abci.v1beta1.TxMsgData)
      com.cosmos.base.abci.v1beta1.TxMsgDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cosmos.base.abci.v1beta1.AbciProto.internal_static_cosmos_base_abci_v1beta1_TxMsgData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cosmos.base.abci.v1beta1.AbciProto.internal_static_cosmos_base_abci_v1beta1_TxMsgData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cosmos.base.abci.v1beta1.TxMsgData.class, com.cosmos.base.abci.v1beta1.TxMsgData.Builder.class);
    }

    // Construct using com.cosmos.base.abci.v1beta1.TxMsgData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
      } else {
        data_ = null;
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cosmos.base.abci.v1beta1.AbciProto.internal_static_cosmos_base_abci_v1beta1_TxMsgData_descriptor;
    }

    @java.lang.Override
    public com.cosmos.base.abci.v1beta1.TxMsgData getDefaultInstanceForType() {
      return com.cosmos.base.abci.v1beta1.TxMsgData.getDefaultInstance();
    }

    @java.lang.Override
    public com.cosmos.base.abci.v1beta1.TxMsgData build() {
      com.cosmos.base.abci.v1beta1.TxMsgData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cosmos.base.abci.v1beta1.TxMsgData buildPartial() {
      com.cosmos.base.abci.v1beta1.TxMsgData result = new com.cosmos.base.abci.v1beta1.TxMsgData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.cosmos.base.abci.v1beta1.TxMsgData result) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
    }

    private void buildPartial0(com.cosmos.base.abci.v1beta1.TxMsgData result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cosmos.base.abci.v1beta1.TxMsgData) {
        return mergeFrom((com.cosmos.base.abci.v1beta1.TxMsgData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cosmos.base.abci.v1beta1.TxMsgData other) {
      if (other == com.cosmos.base.abci.v1beta1.TxMsgData.getDefaultInstance()) return this;
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.cosmos.base.abci.v1beta1.MsgData m =
                  input.readMessage(
                      com.cosmos.base.abci.v1beta1.MsgData.parser(),
                      extensionRegistry);
              if (dataBuilder_ == null) {
                ensureDataIsMutable();
                data_.add(m);
              } else {
                dataBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cosmos.base.abci.v1beta1.MsgData> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        data_ = new java.util.ArrayList<com.cosmos.base.abci.v1beta1.MsgData>(data_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cosmos.base.abci.v1beta1.MsgData, com.cosmos.base.abci.v1beta1.MsgData.Builder, com.cosmos.base.abci.v1beta1.MsgDataOrBuilder> dataBuilder_;

    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public java.util.List<com.cosmos.base.abci.v1beta1.MsgData> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public com.cosmos.base.abci.v1beta1.MsgData getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder setData(
        int index, com.cosmos.base.abci.v1beta1.MsgData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder setData(
        int index, com.cosmos.base.abci.v1beta1.MsgData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder addData(com.cosmos.base.abci.v1beta1.MsgData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder addData(
        int index, com.cosmos.base.abci.v1beta1.MsgData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder addData(
        com.cosmos.base.abci.v1beta1.MsgData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder addData(
        int index, com.cosmos.base.abci.v1beta1.MsgData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends com.cosmos.base.abci.v1beta1.MsgData> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public com.cosmos.base.abci.v1beta1.MsgData.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public com.cosmos.base.abci.v1beta1.MsgDataOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public java.util.List<? extends com.cosmos.base.abci.v1beta1.MsgDataOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public com.cosmos.base.abci.v1beta1.MsgData.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          com.cosmos.base.abci.v1beta1.MsgData.getDefaultInstance());
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public com.cosmos.base.abci.v1beta1.MsgData.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, com.cosmos.base.abci.v1beta1.MsgData.getDefaultInstance());
    }
    /**
     * <code>repeated .cosmos.base.abci.v1beta1.MsgData data = 1 [json_name = "data"];</code>
     */
    public java.util.List<com.cosmos.base.abci.v1beta1.MsgData.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cosmos.base.abci.v1beta1.MsgData, com.cosmos.base.abci.v1beta1.MsgData.Builder, com.cosmos.base.abci.v1beta1.MsgDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cosmos.base.abci.v1beta1.MsgData, com.cosmos.base.abci.v1beta1.MsgData.Builder, com.cosmos.base.abci.v1beta1.MsgDataOrBuilder>(
                data_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cosmos.base.abci.v1beta1.TxMsgData)
  }

  // @@protoc_insertion_point(class_scope:cosmos.base.abci.v1beta1.TxMsgData)
  private static final com.cosmos.base.abci.v1beta1.TxMsgData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cosmos.base.abci.v1beta1.TxMsgData();
  }

  public static com.cosmos.base.abci.v1beta1.TxMsgData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TxMsgData>
      PARSER = new com.google.protobuf.AbstractParser<TxMsgData>() {
    @java.lang.Override
    public TxMsgData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TxMsgData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TxMsgData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cosmos.base.abci.v1beta1.TxMsgData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

