// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/transactions/mint/message.proto

package com.assetmantle.modules.assets.transactions.mint;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_assets_transactions_mint_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_assets_transactions_mint_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&assets/transactions/mint/message.proto" +
      "\022,assetmantle.modules.assets.transaction" +
      "s.mint\032 ids/base/classification_id.proto" +
      "\032\032ids/base/identity_id.proto\032\036lists/base" +
      "/property_list.proto\"\206\005\n\007Message\022\022\n\004from" +
      "\030\001 \001(\tR\004from\022A\n\010from_i_d\030\002 \001(\0132\'.assetma" +
      "ntle.schema.ids.base.IdentityIDR\006fromID\022" +
      "=\n\006to_i_d\030\003 \001(\0132\'.assetmantle.schema.ids" +
      ".base.IdentityIDR\004toID\022[\n\022classification" +
      "_i_d\030\004 \001(\0132-.assetmantle.schema.ids.base" +
      ".ClassificationIDR\020classificationID\022g\n\031i" +
      "mmutable_meta_properties\030\005 \001(\0132+.assetma" +
      "ntle.schema.lists.base.PropertyListR\027imm" +
      "utableMetaProperties\022^\n\024immutable_proper" +
      "ties\030\006 \001(\0132+.assetmantle.schema.lists.ba" +
      "se.PropertyListR\023immutableProperties\022c\n\027" +
      "mutable_meta_properties\030\007 \001(\0132+.assetman" +
      "tle.schema.lists.base.PropertyListR\025muta" +
      "bleMetaProperties\022Z\n\022mutable_properties\030" +
      "\010 \001(\0132+.assetmantle.schema.lists.base.Pr" +
      "opertyListR\021mutablePropertiesB\321\002\n0com.as" +
      "setmantle.modules.assets.transactions.mi" +
      "ntB\014MessageProtoP\001Z9github.com/AssetMant" +
      "le/modules/x/assets/transactions/mint\242\002\005" +
      "AMATM\252\002,Assetmantle.Modules.Assets.Trans" +
      "actions.Mint\312\002,Assetmantle\\Modules\\Asset" +
      "s\\Transactions\\Mint\342\0028Assetmantle\\Module" +
      "s\\Assets\\Transactions\\Mint\\GPBMetadata\352\002" +
      "0Assetmantle::Modules::Assets::Transacti" +
      "ons::Mintb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.schema.ids.base.ClassificationIdProto.getDescriptor(),
          com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor(),
          com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_assets_transactions_mint_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_assets_transactions_mint_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_assets_transactions_mint_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "ClassificationID", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.assetmantle.schema.ids.base.ClassificationIdProto.getDescriptor();
    com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor();
    com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
