// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/consensus/types.proto

package com.tendermint.consensus;

public interface VoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.consensus.Vote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tendermint.types.Vote vote = 1 [json_name = "vote"];</code>
   * @return Whether the vote field is set.
   */
  boolean hasVote();
  /**
   * <code>.tendermint.types.Vote vote = 1 [json_name = "vote"];</code>
   * @return The vote.
   */
  com.tendermint.types.Vote getVote();
  /**
   * <code>.tendermint.types.Vote vote = 1 [json_name = "vote"];</code>
   */
  com.tendermint.types.VoteOrBuilder getVoteOrBuilder();
}
