// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/consensus/wal.proto

package com.tendermint.consensus;

public final class WalProto {
  private WalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_consensus_MsgInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_consensus_MsgInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_consensus_TimeoutInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_consensus_TimeoutInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_consensus_EndHeight_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_consensus_EndHeight_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_consensus_WALMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_consensus_WALMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tendermint_consensus_TimedWALMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tendermint_consensus_TimedWALMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036tendermint/consensus/wal.proto\022\024tender" +
      "mint.consensus\032\024gogoproto/gogo.proto\032 te" +
      "ndermint/consensus/types.proto\032\035tendermi" +
      "nt/types/events.proto\032\036google/protobuf/d" +
      "uration.proto\032\037google/protobuf/timestamp" +
      ".proto\"e\n\007MsgInfo\0225\n\003msg\030\001 \001(\0132\035.tenderm" +
      "int.consensus.MessageB\004\310\336\037\000R\003msg\022#\n\007peer" +
      "_id\030\002 \001(\tB\n\342\336\037\006PeerIDR\006peerId\"\220\001\n\013Timeou" +
      "tInfo\022?\n\010duration\030\001 \001(\0132\031.google.protobu" +
      "f.DurationB\010\310\336\037\000\230\337\037\001R\010duration\022\026\n\006height" +
      "\030\002 \001(\003R\006height\022\024\n\005round\030\003 \001(\005R\005round\022\022\n\004" +
      "step\030\004 \001(\rR\004step\"#\n\tEndHeight\022\026\n\006height\030" +
      "\001 \001(\003R\006height\"\267\002\n\nWALMessage\022\\\n\026event_da" +
      "ta_round_state\030\001 \001(\0132%.tendermint.types." +
      "EventDataRoundStateH\000R\023eventDataRoundSta" +
      "te\022:\n\010msg_info\030\002 \001(\0132\035.tendermint.consen" +
      "sus.MsgInfoH\000R\007msgInfo\022F\n\014timeout_info\030\003" +
      " \001(\0132!.tendermint.consensus.TimeoutInfoH" +
      "\000R\013timeoutInfo\022@\n\nend_height\030\004 \001(\0132\037.ten" +
      "dermint.consensus.EndHeightH\000R\tendHeight" +
      "B\005\n\003sum\"\177\n\017TimedWALMessage\0228\n\004time\030\001 \001(\013" +
      "2\032.google.protobuf.TimestampB\010\310\336\037\000\220\337\037\001R\004" +
      "time\0222\n\003msg\030\002 \001(\0132 .tendermint.consensus" +
      ".WALMessageR\003msgB\322\001\n\030com.tendermint.cons" +
      "ensusB\010WalProtoP\001Z;github.com/tendermint" +
      "/tendermint/proto/tendermint/consensus\242\002" +
      "\003TCX\252\002\024Tendermint.Consensus\312\002\024Tendermint" +
      "\\Consensus\342\002 Tendermint\\Consensus\\GPBMet" +
      "adata\352\002\025Tendermint::Consensusb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.tendermint.consensus.TypesProto.getDescriptor(),
          com.tendermint.types.EventsProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tendermint_consensus_MsgInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tendermint_consensus_MsgInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_consensus_MsgInfo_descriptor,
        new java.lang.String[] { "Msg", "PeerId", });
    internal_static_tendermint_consensus_TimeoutInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tendermint_consensus_TimeoutInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_consensus_TimeoutInfo_descriptor,
        new java.lang.String[] { "Duration", "Height", "Round", "Step", });
    internal_static_tendermint_consensus_EndHeight_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tendermint_consensus_EndHeight_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_consensus_EndHeight_descriptor,
        new java.lang.String[] { "Height", });
    internal_static_tendermint_consensus_WALMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tendermint_consensus_WALMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_consensus_WALMessage_descriptor,
        new java.lang.String[] { "EventDataRoundState", "MsgInfo", "TimeoutInfo", "EndHeight", "Sum", });
    internal_static_tendermint_consensus_TimedWALMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tendermint_consensus_TimedWALMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tendermint_consensus_TimedWALMessage_descriptor,
        new java.lang.String[] { "Time", "Msg", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.customname);
    registry.add(com.gogoproto.GogoProto.nullable);
    registry.add(com.gogoproto.GogoProto.stdduration);
    registry.add(com.gogoproto.GogoProto.stdtime);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.tendermint.consensus.TypesProto.getDescriptor();
    com.tendermint.types.EventsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
