// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: splits/queries/supply/service.proto

package com.assetmantle.modules.splits.queries.supply;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#splits/queries/supply/service.proto\022)a" +
      "ssetmantle.modules.splits.queries.supply" +
      "\032\034google/api/annotations.proto\032)splits/q" +
      "ueries/supply/query_request.proto\032*split" +
      "s/queries/supply/query_response.proto2\254\001" +
      "\n\005Query\022\242\001\n\006Handle\0227.assetmantle.modules" +
      ".splits.queries.supply.QueryRequest\0328.as" +
      "setmantle.modules.splits.queries.supply." +
      "QueryResponse\"%\202\323\344\223\002\037\022\035/mantle/splits/v1" +
      "beta1/supplyB\277\002\n-com.assetmantle.modules" +
      ".splits.queries.supplyB\014ServiceProtoP\001Z6" +
      "github.com/AssetMantle/modules/x/splits/" +
      "queries/supply\242\002\005AMSQS\252\002)Assetmantle.Mod" +
      "ules.Splits.Queries.Supply\312\002)Assetmantle" +
      "\\Modules\\Splits\\Queries\\Supply\342\0025Assetma" +
      "ntle\\Modules\\Splits\\Queries\\Supply\\GPBMe" +
      "tadata\352\002-Assetmantle::Modules::Splits::Q" +
      "ueries::Supplyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assetmantle.modules.splits.queries.supply.QueryRequestProto.getDescriptor(),
          com.assetmantle.modules.splits.queries.supply.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assetmantle.modules.splits.queries.supply.QueryRequestProto.getDescriptor();
    com.assetmantle.modules.splits.queries.supply.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
