// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identities/queries/identities/query_response.proto

package com.assetmantle.modules.identities.queries.identities;

public interface QueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assetmantle.modules.identities.queries.identities.QueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .assetmantle.modules.identities.record.Record list = 1 [json_name = "list"];</code>
   */
  java.util.List<com.assetmantle.modules.identities.record.Record> 
      getListList();
  /**
   * <code>repeated .assetmantle.modules.identities.record.Record list = 1 [json_name = "list"];</code>
   */
  com.assetmantle.modules.identities.record.Record getList(int index);
  /**
   * <code>repeated .assetmantle.modules.identities.record.Record list = 1 [json_name = "list"];</code>
   */
  int getListCount();
  /**
   * <code>repeated .assetmantle.modules.identities.record.Record list = 1 [json_name = "list"];</code>
   */
  java.util.List<? extends com.assetmantle.modules.identities.record.RecordOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .assetmantle.modules.identities.record.Record list = 1 [json_name = "list"];</code>
   */
  com.assetmantle.modules.identities.record.RecordOrBuilder getListOrBuilder(
      int index);
}
