// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/bank/v1beta1/genesis.proto

package com.cosmos.bank.v1beta1;

public final class GenesisProto {
  private GenesisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_GenesisState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_GenesisState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_Balance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_Balance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!cosmos/bank/v1beta1/genesis.proto\022\023cos" +
      "mos.bank.v1beta1\032\024gogoproto/gogo.proto\032\036" +
      "cosmos/base/v1beta1/coin.proto\032\036cosmos/b" +
      "ank/v1beta1/bank.proto\"\323\002\n\014GenesisState\022" +
      "9\n\006params\030\001 \001(\0132\033.cosmos.bank.v1beta1.Pa" +
      "ramsB\004\310\336\037\000R\006params\022>\n\010balances\030\002 \003(\0132\034.c" +
      "osmos.bank.v1beta1.BalanceB\004\310\336\037\000R\010balanc" +
      "es\022c\n\006supply\030\003 \003(\0132\031.cosmos.base.v1beta1" +
      ".CoinB0\310\336\037\000\252\337\037(github.com/cosmos/cosmos-" +
      "sdk/types.CoinsR\006supply\022c\n\016denom_metadat" +
      "a\030\004 \003(\0132\035.cosmos.bank.v1beta1.MetadataB\035" +
      "\310\336\037\000\362\336\037\025yaml:\"denom_metadata\"R\rdenomMeta" +
      "data\"\220\001\n\007Balance\022\030\n\007address\030\001 \001(\tR\007addre" +
      "ss\022a\n\005coins\030\002 \003(\0132\031.cosmos.base.v1beta1." +
      "CoinB0\310\336\037\000\252\337\037(github.com/cosmos/cosmos-s" +
      "dk/types.CoinsR\005coins:\010\210\240\037\000\350\240\037\000B\300\001\n\027com." +
      "cosmos.bank.v1beta1B\014GenesisProtoP\001Z)git" +
      "hub.com/cosmos/cosmos-sdk/x/bank/types\242\002" +
      "\003CBX\252\002\023Cosmos.Bank.V1beta1\312\002\023Cosmos\\Bank" +
      "\\V1beta1\342\002\037Cosmos\\Bank\\V1beta1\\GPBMetada" +
      "ta\352\002\025Cosmos::Bank::V1beta1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.cosmos.base.v1beta1.CoinProto.getDescriptor(),
          com.cosmos.bank.v1beta1.BankProto.getDescriptor(),
        });
    internal_static_cosmos_bank_v1beta1_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_bank_v1beta1_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_GenesisState_descriptor,
        new java.lang.String[] { "Params", "Balances", "Supply", "DenomMetadata", });
    internal_static_cosmos_bank_v1beta1_Balance_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_bank_v1beta1_Balance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_Balance_descriptor,
        new java.lang.String[] { "Address", "Coins", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.castrepeated);
    registry.add(com.gogoproto.GogoProto.equal);
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    registry.add(com.gogoproto.GogoProto.moretags);
    registry.add(com.gogoproto.GogoProto.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.cosmos.base.v1beta1.CoinProto.getDescriptor();
    com.cosmos.bank.v1beta1.BankProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
