// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/bank/v1beta1/query.proto

package com.cosmos.bank.v1beta1;

public final class QueryProto {
  private QueryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryAllBalancesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryAllBalancesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryAllBalancesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryAllBalancesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryTotalSupplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryTotalSupplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryTotalSupplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryTotalSupplyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QuerySupplyOfRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QuerySupplyOfRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QuerySupplyOfResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QuerySupplyOfResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryParamsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryParamsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryParamsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryParamsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryDenomMetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryDenomMetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_bank_v1beta1_QueryDenomMetadataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_bank_v1beta1_QueryDenomMetadataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037cosmos/bank/v1beta1/query.proto\022\023cosmo" +
      "s.bank.v1beta1\032*cosmos/base/query/v1beta" +
      "1/pagination.proto\032\024gogoproto/gogo.proto" +
      "\032\034google/api/annotations.proto\032\036cosmos/b" +
      "ase/v1beta1/coin.proto\032\036cosmos/bank/v1be" +
      "ta1/bank.proto\"O\n\023QueryBalanceRequest\022\030\n" +
      "\007address\030\001 \001(\tR\007address\022\024\n\005denom\030\002 \001(\tR\005" +
      "denom:\010\210\240\037\000\350\240\037\000\"K\n\024QueryBalanceResponse\022" +
      "3\n\007balance\030\001 \001(\0132\031.cosmos.base.v1beta1.C" +
      "oinR\007balance\"\205\001\n\027QueryAllBalancesRequest" +
      "\022\030\n\007address\030\001 \001(\tR\007address\022F\n\npagination" +
      "\030\002 \001(\0132&.cosmos.base.query.v1beta1.PageR" +
      "equestR\npagination:\010\210\240\037\000\350\240\037\000\"\314\001\n\030QueryAl" +
      "lBalancesResponse\022g\n\010balances\030\001 \003(\0132\031.co" +
      "smos.base.v1beta1.CoinB0\310\336\037\000\252\337\037(github.c" +
      "om/cosmos/cosmos-sdk/types.CoinsR\010balanc" +
      "es\022G\n\npagination\030\002 \001(\0132\'.cosmos.base.que" +
      "ry.v1beta1.PageResponseR\npagination\"\213\001\n\035" +
      "QuerySpendableBalancesRequest\022\030\n\007address" +
      "\030\001 \001(\tR\007address\022F\n\npagination\030\002 \001(\0132&.co" +
      "smos.base.query.v1beta1.PageRequestR\npag" +
      "ination:\010\210\240\037\000\350\240\037\000\"\322\001\n\036QuerySpendableBala" +
      "ncesResponse\022g\n\010balances\030\001 \003(\0132\031.cosmos." +
      "base.v1beta1.CoinB0\310\336\037\000\252\337\037(github.com/co" +
      "smos/cosmos-sdk/types.CoinsR\010balances\022G\n" +
      "\npagination\030\002 \001(\0132\'.cosmos.base.query.v1" +
      "beta1.PageResponseR\npagination\"k\n\027QueryT" +
      "otalSupplyRequest\022F\n\npagination\030\001 \001(\0132&." +
      "cosmos.base.query.v1beta1.PageRequestR\np" +
      "agination:\010\210\240\037\000\350\240\037\000\"\310\001\n\030QueryTotalSupply" +
      "Response\022c\n\006supply\030\001 \003(\0132\031.cosmos.base.v" +
      "1beta1.CoinB0\310\336\037\000\252\337\037(github.com/cosmos/c" +
      "osmos-sdk/types.CoinsR\006supply\022G\n\npaginat" +
      "ion\030\002 \001(\0132\'.cosmos.base.query.v1beta1.Pa" +
      "geResponseR\npagination\",\n\024QuerySupplyOfR" +
      "equest\022\024\n\005denom\030\001 \001(\tR\005denom\"P\n\025QuerySup" +
      "plyOfResponse\0227\n\006amount\030\001 \001(\0132\031.cosmos.b" +
      "ase.v1beta1.CoinB\004\310\336\037\000R\006amount\"\024\n\022QueryP" +
      "aramsRequest\"P\n\023QueryParamsResponse\0229\n\006p" +
      "arams\030\001 \001(\0132\033.cosmos.bank.v1beta1.Params" +
      "B\004\310\336\037\000R\006params\"d\n\032QueryDenomsMetadataReq" +
      "uest\022F\n\npagination\030\001 \001(\0132&.cosmos.base.q" +
      "uery.v1beta1.PageRequestR\npagination\"\251\001\n" +
      "\033QueryDenomsMetadataResponse\022A\n\tmetadata" +
      "s\030\001 \003(\0132\035.cosmos.bank.v1beta1.MetadataB\004" +
      "\310\336\037\000R\tmetadatas\022G\n\npagination\030\002 \001(\0132\'.co" +
      "smos.base.query.v1beta1.PageResponseR\npa" +
      "gination\"1\n\031QueryDenomMetadataRequest\022\024\n" +
      "\005denom\030\001 \001(\tR\005denom\"]\n\032QueryDenomMetadat" +
      "aResponse\022?\n\010metadata\030\001 \001(\0132\035.cosmos.ban" +
      "k.v1beta1.MetadataB\004\310\336\037\000R\010metadata2\355\t\n\005Q" +
      "uery\022\230\001\n\007Balance\022(.cosmos.bank.v1beta1.Q" +
      "ueryBalanceRequest\032).cosmos.bank.v1beta1" +
      ".QueryBalanceResponse\"8\202\323\344\223\0022\0220/cosmos/b" +
      "ank/v1beta1/balances/{address}/by_denom\022" +
      "\233\001\n\013AllBalances\022,.cosmos.bank.v1beta1.Qu" +
      "eryAllBalancesRequest\032-.cosmos.bank.v1be" +
      "ta1.QueryAllBalancesResponse\"/\202\323\344\223\002)\022\'/c" +
      "osmos/bank/v1beta1/balances/{address}\022\267\001" +
      "\n\021SpendableBalances\0222.cosmos.bank.v1beta" +
      "1.QuerySpendableBalancesRequest\0323.cosmos" +
      ".bank.v1beta1.QuerySpendableBalancesResp" +
      "onse\"9\202\323\344\223\0023\0221/cosmos/bank/v1beta1/spend" +
      "able_balances/{address}\022\217\001\n\013TotalSupply\022" +
      ",.cosmos.bank.v1beta1.QueryTotalSupplyRe" +
      "quest\032-.cosmos.bank.v1beta1.QueryTotalSu" +
      "pplyResponse\"#\202\323\344\223\002\035\022\033/cosmos/bank/v1bet" +
      "a1/supply\022\216\001\n\010SupplyOf\022).cosmos.bank.v1b" +
      "eta1.QuerySupplyOfRequest\032*.cosmos.bank." +
      "v1beta1.QuerySupplyOfResponse\"+\202\323\344\223\002%\022#/" +
      "cosmos/bank/v1beta1/supply/{denom}\022\200\001\n\006P" +
      "arams\022\'.cosmos.bank.v1beta1.QueryParamsR" +
      "equest\032(.cosmos.bank.v1beta1.QueryParams" +
      "Response\"#\202\323\344\223\002\035\022\033/cosmos/bank/v1beta1/p" +
      "arams\022\246\001\n\rDenomMetadata\022..cosmos.bank.v1" +
      "beta1.QueryDenomMetadataRequest\032/.cosmos" +
      ".bank.v1beta1.QueryDenomMetadataResponse" +
      "\"4\202\323\344\223\002.\022,/cosmos/bank/v1beta1/denoms_me" +
      "tadata/{denom}\022\241\001\n\016DenomsMetadata\022/.cosm" +
      "os.bank.v1beta1.QueryDenomsMetadataReque" +
      "st\0320.cosmos.bank.v1beta1.QueryDenomsMeta" +
      "dataResponse\",\202\323\344\223\002&\022$/cosmos/bank/v1bet" +
      "a1/denoms_metadataB\276\001\n\027com.cosmos.bank.v" +
      "1beta1B\nQueryProtoP\001Z)github.com/cosmos/" +
      "cosmos-sdk/x/bank/types\242\002\003CBX\252\002\023Cosmos.B" +
      "ank.V1beta1\312\002\023Cosmos\\Bank\\V1beta1\342\002\037Cosm" +
      "os\\Bank\\V1beta1\\GPBMetadata\352\002\025Cosmos::Ba" +
      "nk::V1beta1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cosmos.base.query.v1beta1.PaginationProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.cosmos.base.v1beta1.CoinProto.getDescriptor(),
          com.cosmos.bank.v1beta1.BankProto.getDescriptor(),
        });
    internal_static_cosmos_bank_v1beta1_QueryBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_bank_v1beta1_QueryBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryBalanceRequest_descriptor,
        new java.lang.String[] { "Address", "Denom", });
    internal_static_cosmos_bank_v1beta1_QueryBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_bank_v1beta1_QueryBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryBalanceResponse_descriptor,
        new java.lang.String[] { "Balance", });
    internal_static_cosmos_bank_v1beta1_QueryAllBalancesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cosmos_bank_v1beta1_QueryAllBalancesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryAllBalancesRequest_descriptor,
        new java.lang.String[] { "Address", "Pagination", });
    internal_static_cosmos_bank_v1beta1_QueryAllBalancesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cosmos_bank_v1beta1_QueryAllBalancesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryAllBalancesResponse_descriptor,
        new java.lang.String[] { "Balances", "Pagination", });
    internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesRequest_descriptor,
        new java.lang.String[] { "Address", "Pagination", });
    internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QuerySpendableBalancesResponse_descriptor,
        new java.lang.String[] { "Balances", "Pagination", });
    internal_static_cosmos_bank_v1beta1_QueryTotalSupplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cosmos_bank_v1beta1_QueryTotalSupplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryTotalSupplyRequest_descriptor,
        new java.lang.String[] { "Pagination", });
    internal_static_cosmos_bank_v1beta1_QueryTotalSupplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cosmos_bank_v1beta1_QueryTotalSupplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryTotalSupplyResponse_descriptor,
        new java.lang.String[] { "Supply", "Pagination", });
    internal_static_cosmos_bank_v1beta1_QuerySupplyOfRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_cosmos_bank_v1beta1_QuerySupplyOfRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QuerySupplyOfRequest_descriptor,
        new java.lang.String[] { "Denom", });
    internal_static_cosmos_bank_v1beta1_QuerySupplyOfResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_cosmos_bank_v1beta1_QuerySupplyOfResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QuerySupplyOfResponse_descriptor,
        new java.lang.String[] { "Amount", });
    internal_static_cosmos_bank_v1beta1_QueryParamsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_cosmos_bank_v1beta1_QueryParamsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryParamsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_cosmos_bank_v1beta1_QueryParamsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_cosmos_bank_v1beta1_QueryParamsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryParamsResponse_descriptor,
        new java.lang.String[] { "Params", });
    internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataRequest_descriptor,
        new java.lang.String[] { "Pagination", });
    internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryDenomsMetadataResponse_descriptor,
        new java.lang.String[] { "Metadatas", "Pagination", });
    internal_static_cosmos_bank_v1beta1_QueryDenomMetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_cosmos_bank_v1beta1_QueryDenomMetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryDenomMetadataRequest_descriptor,
        new java.lang.String[] { "Denom", });
    internal_static_cosmos_bank_v1beta1_QueryDenomMetadataResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_cosmos_bank_v1beta1_QueryDenomMetadataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_bank_v1beta1_QueryDenomMetadataResponse_descriptor,
        new java.lang.String[] { "Metadata", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.castrepeated);
    registry.add(com.gogoproto.GogoProto.equal);
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    registry.add(com.gogoproto.GogoProto.nullable);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.cosmos.base.query.v1beta1.PaginationProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.cosmos.base.v1beta1.CoinProto.getDescriptor();
    com.cosmos.bank.v1beta1.BankProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
