// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: confio/proofs.proto

package com.ics23;

public interface CompressedExistenceProofOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ics23.CompressedExistenceProof)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
   * @return Whether the leaf field is set.
   */
  boolean hasLeaf();
  /**
   * <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
   * @return The leaf.
   */
  com.ics23.LeafOp getLeaf();
  /**
   * <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
   */
  com.ics23.LeafOpOrBuilder getLeafOrBuilder();

  /**
   * <pre>
   * these are indexes into the lookup_inners table in CompressedBatchProof
   * </pre>
   *
   * <code>repeated int32 path = 4 [json_name = "path"];</code>
   * @return A list containing the path.
   */
  java.util.List<java.lang.Integer> getPathList();
  /**
   * <pre>
   * these are indexes into the lookup_inners table in CompressedBatchProof
   * </pre>
   *
   * <code>repeated int32 path = 4 [json_name = "path"];</code>
   * @return The count of path.
   */
  int getPathCount();
  /**
   * <pre>
   * these are indexes into the lookup_inners table in CompressedBatchProof
   * </pre>
   *
   * <code>repeated int32 path = 4 [json_name = "path"];</code>
   * @param index The index of the element to return.
   * @return The path at the given index.
   */
  int getPath(int index);
}
