// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: confio/proofs.proto

package com.ics23;

public interface ExistenceProofOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ics23.ExistenceProof)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
   * @return Whether the leaf field is set.
   */
  boolean hasLeaf();
  /**
   * <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
   * @return The leaf.
   */
  com.ics23.LeafOp getLeaf();
  /**
   * <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
   */
  com.ics23.LeafOpOrBuilder getLeafOrBuilder();

  /**
   * <code>repeated .ics23.InnerOp path = 4 [json_name = "path"];</code>
   */
  java.util.List<com.ics23.InnerOp> 
      getPathList();
  /**
   * <code>repeated .ics23.InnerOp path = 4 [json_name = "path"];</code>
   */
  com.ics23.InnerOp getPath(int index);
  /**
   * <code>repeated .ics23.InnerOp path = 4 [json_name = "path"];</code>
   */
  int getPathCount();
  /**
   * <code>repeated .ics23.InnerOp path = 4 [json_name = "path"];</code>
   */
  java.util.List<? extends com.ics23.InnerOpOrBuilder> 
      getPathOrBuilderList();
  /**
   * <code>repeated .ics23.InnerOp path = 4 [json_name = "path"];</code>
   */
  com.ics23.InnerOpOrBuilder getPathOrBuilder(
      int index);
}
