// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identities/transactions/deputize/message.proto

package com.assetmantle.modules.identities.transactions.deputize;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assetmantle.modules.identities.transactions.deputize.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from = 1 [json_name = "from"];</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 1 [json_name = "from"];</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>.assetmantle.schema.ids.base.IdentityID from_i_d = 2 [json_name = "fromID"];</code>
   * @return Whether the fromID field is set.
   */
  boolean hasFromID();
  /**
   * <code>.assetmantle.schema.ids.base.IdentityID from_i_d = 2 [json_name = "fromID"];</code>
   * @return The fromID.
   */
  com.assetmantle.schema.ids.base.IdentityID getFromID();
  /**
   * <code>.assetmantle.schema.ids.base.IdentityID from_i_d = 2 [json_name = "fromID"];</code>
   */
  com.assetmantle.schema.ids.base.IdentityIDOrBuilder getFromIDOrBuilder();

  /**
   * <code>.assetmantle.schema.ids.base.IdentityID to_i_d = 3 [json_name = "toID"];</code>
   * @return Whether the toID field is set.
   */
  boolean hasToID();
  /**
   * <code>.assetmantle.schema.ids.base.IdentityID to_i_d = 3 [json_name = "toID"];</code>
   * @return The toID.
   */
  com.assetmantle.schema.ids.base.IdentityID getToID();
  /**
   * <code>.assetmantle.schema.ids.base.IdentityID to_i_d = 3 [json_name = "toID"];</code>
   */
  com.assetmantle.schema.ids.base.IdentityIDOrBuilder getToIDOrBuilder();

  /**
   * <code>.assetmantle.schema.ids.base.ClassificationID classification_i_d = 4 [json_name = "classificationID"];</code>
   * @return Whether the classificationID field is set.
   */
  boolean hasClassificationID();
  /**
   * <code>.assetmantle.schema.ids.base.ClassificationID classification_i_d = 4 [json_name = "classificationID"];</code>
   * @return The classificationID.
   */
  com.assetmantle.schema.ids.base.ClassificationID getClassificationID();
  /**
   * <code>.assetmantle.schema.ids.base.ClassificationID classification_i_d = 4 [json_name = "classificationID"];</code>
   */
  com.assetmantle.schema.ids.base.ClassificationIDOrBuilder getClassificationIDOrBuilder();

  /**
   * <code>.assetmantle.schema.lists.base.PropertyList maintained_properties = 5 [json_name = "maintainedProperties"];</code>
   * @return Whether the maintainedProperties field is set.
   */
  boolean hasMaintainedProperties();
  /**
   * <code>.assetmantle.schema.lists.base.PropertyList maintained_properties = 5 [json_name = "maintainedProperties"];</code>
   * @return The maintainedProperties.
   */
  com.assetmantle.schema.lists.base.PropertyList getMaintainedProperties();
  /**
   * <code>.assetmantle.schema.lists.base.PropertyList maintained_properties = 5 [json_name = "maintainedProperties"];</code>
   */
  com.assetmantle.schema.lists.base.PropertyListOrBuilder getMaintainedPropertiesOrBuilder();

  /**
   * <code>bool can_issue_identity = 6 [json_name = "canIssueIdentity"];</code>
   * @return The canIssueIdentity.
   */
  boolean getCanIssueIdentity();

  /**
   * <code>bool can_quash_identity = 7 [json_name = "canQuashIdentity"];</code>
   * @return The canQuashIdentity.
   */
  boolean getCanQuashIdentity();

  /**
   * <code>bool can_add_maintainer = 8 [json_name = "canAddMaintainer"];</code>
   * @return The canAddMaintainer.
   */
  boolean getCanAddMaintainer();

  /**
   * <code>bool can_remove_maintainer = 9 [json_name = "canRemoveMaintainer"];</code>
   * @return The canRemoveMaintainer.
   */
  boolean getCanRemoveMaintainer();

  /**
   * <code>bool can_mutate_maintainer = 10 [json_name = "canMutateMaintainer"];</code>
   * @return The canMutateMaintainer.
   */
  boolean getCanMutateMaintainer();
}
