// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/abci/types.proto

package com.tendermint.abci;

public interface EventAttributeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.abci.EventAttribute)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <pre>
   * nondeterministic
   * </pre>
   *
   * <code>bool index = 3 [json_name = "index"];</code>
   * @return The index.
   */
  boolean getIndex();
}
