// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/abci/types.proto

package com.tendermint.abci;

public interface RequestEndBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.abci.RequestEndBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 height = 1 [json_name = "height"];</code>
   * @return The height.
   */
  long getHeight();
}
