// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/abci/types.proto

package com.tendermint.abci;

public interface ResponseBeginBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.abci.ResponseBeginBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tendermint.abci.Event events = 1 [json_name = "events", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "events,omitempty"];</code>
   */
  java.util.List<com.tendermint.abci.Event> 
      getEventsList();
  /**
   * <code>repeated .tendermint.abci.Event events = 1 [json_name = "events", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "events,omitempty"];</code>
   */
  com.tendermint.abci.Event getEvents(int index);
  /**
   * <code>repeated .tendermint.abci.Event events = 1 [json_name = "events", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "events,omitempty"];</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .tendermint.abci.Event events = 1 [json_name = "events", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "events,omitempty"];</code>
   */
  java.util.List<? extends com.tendermint.abci.EventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .tendermint.abci.Event events = 1 [json_name = "events", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "events,omitempty"];</code>
   */
  com.tendermint.abci.EventOrBuilder getEventsOrBuilder(
      int index);
}
