// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/abci/types.proto

package com.tendermint.abci;

public interface VoteInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.abci.VoteInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tendermint.abci.Validator validator = 1 [json_name = "validator", (.gogoproto.nullable) = false];</code>
   * @return Whether the validator field is set.
   */
  boolean hasValidator();
  /**
   * <code>.tendermint.abci.Validator validator = 1 [json_name = "validator", (.gogoproto.nullable) = false];</code>
   * @return The validator.
   */
  com.tendermint.abci.Validator getValidator();
  /**
   * <code>.tendermint.abci.Validator validator = 1 [json_name = "validator", (.gogoproto.nullable) = false];</code>
   */
  com.tendermint.abci.ValidatorOrBuilder getValidatorOrBuilder();

  /**
   * <code>bool signed_last_block = 2 [json_name = "signedLastBlock"];</code>
   * @return The signedLastBlock.
   */
  boolean getSignedLastBlock();
}
