// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identities/transactions/define/service.proto

package com.assetmantle.modules.identities.transactions.define;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,identities/transactions/define/service" +
      ".proto\0222assetmantle.modules.identities.t" +
      "ransactions.define\032\034google/api/annotatio" +
      "ns.proto\032,identities/transactions/define" +
      "/message.proto\0329identities/transactions/" +
      "define/transaction_response.proto2\271\001\n\003Ms" +
      "g\022\261\001\n\006Handle\022;.assetmantle.modules.ident" +
      "ities.transactions.define.Message\032G.asse" +
      "tmantle.modules.identities.transactions." +
      "define.TransactionResponse\"!\202\323\344\223\002\033\"\031/man" +
      "tle/identities/defineB\365\002\n6com.assetmantl" +
      "e.modules.identities.transactions.define" +
      "B\014ServiceProtoP\001Z?github.com/AssetMantle" +
      "/modules/x/identities/transactions/defin" +
      "e\242\002\005AMITD\252\0022Assetmantle.Modules.Identiti" +
      "es.Transactions.Define\312\0022Assetmantle\\Mod" +
      "ules\\Identities\\Transactions\\Define\342\002>As" +
      "setmantle\\Modules\\Identities\\Transaction" +
      "s\\Define\\GPBMetadata\352\0026Assetmantle::Modu" +
      "les::Identities::Transactions::Defineb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assetmantle.modules.identities.transactions.define.MessageProto.getDescriptor(),
          com.assetmantle.modules.identities.transactions.define.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assetmantle.modules.identities.transactions.define.MessageProto.getDescriptor();
    com.assetmantle.modules.identities.transactions.define.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
