// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/applications/fee/v1/ack.proto

package com.ibc.applications.fee.v1;

public final class AckProto {
  private AckProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ibc_applications_fee_v1_IncentivizedAcknowledgement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ibc_applications_fee_v1_IncentivizedAcknowledgement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!ibc/applications/fee/v1/ack.proto\022\027ibc" +
      ".applications.fee.v1\032\024gogoproto/gogo.pro" +
      "to\"\244\002\n\033IncentivizedAcknowledgement\022O\n\023ap" +
      "p_acknowledgement\030\001 \001(\014B\036\362\336\037\032yaml:\"app_a" +
      "cknowledgement\"R\022appAcknowledgement\022Z\n\027f" +
      "orward_relayer_address\030\002 \001(\tB\"\362\336\037\036yaml:\"" +
      "forward_relayer_address\"R\025forwardRelayer" +
      "Address\022X\n\026underlying_app_success\030\003 \001(\010B" +
      "\"\362\336\037\036yaml:\"underlying_app_successl\"R\024und" +
      "erlyingAppSuccessB\335\001\n\033com.ibc.applicatio" +
      "ns.fee.v1B\010AckProtoP\001Z5github.com/cosmos" +
      "/ibc-go/v4/modules/apps/29-fee/types\242\002\003I" +
      "AF\252\002\027Ibc.Applications.Fee.V1\312\002\027Ibc\\Appli" +
      "cations\\Fee\\V1\342\002#Ibc\\Applications\\Fee\\V1" +
      "\\GPBMetadata\352\002\032Ibc::Applications::Fee::V" +
      "1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_ibc_applications_fee_v1_IncentivizedAcknowledgement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ibc_applications_fee_v1_IncentivizedAcknowledgement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ibc_applications_fee_v1_IncentivizedAcknowledgement_descriptor,
        new java.lang.String[] { "AppAcknowledgement", "ForwardRelayerAddress", "UnderlyingAppSuccess", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.moretags);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
