// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/applications/fee/v1/query.proto

package com.ibc.applications.fee.v1;

public interface QueryFeeEnabledChannelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibc.applications.fee.v1.QueryFeeEnabledChannelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * list of fee enabled channels
   * </pre>
   *
   * <code>repeated .ibc.applications.fee.v1.FeeEnabledChannel fee_enabled_channels = 1 [json_name = "feeEnabledChannels", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"fee_enabled_channels&#92;""];</code>
   */
  java.util.List<com.ibc.applications.fee.v1.FeeEnabledChannel> 
      getFeeEnabledChannelsList();
  /**
   * <pre>
   * list of fee enabled channels
   * </pre>
   *
   * <code>repeated .ibc.applications.fee.v1.FeeEnabledChannel fee_enabled_channels = 1 [json_name = "feeEnabledChannels", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"fee_enabled_channels&#92;""];</code>
   */
  com.ibc.applications.fee.v1.FeeEnabledChannel getFeeEnabledChannels(int index);
  /**
   * <pre>
   * list of fee enabled channels
   * </pre>
   *
   * <code>repeated .ibc.applications.fee.v1.FeeEnabledChannel fee_enabled_channels = 1 [json_name = "feeEnabledChannels", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"fee_enabled_channels&#92;""];</code>
   */
  int getFeeEnabledChannelsCount();
  /**
   * <pre>
   * list of fee enabled channels
   * </pre>
   *
   * <code>repeated .ibc.applications.fee.v1.FeeEnabledChannel fee_enabled_channels = 1 [json_name = "feeEnabledChannels", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"fee_enabled_channels&#92;""];</code>
   */
  java.util.List<? extends com.ibc.applications.fee.v1.FeeEnabledChannelOrBuilder> 
      getFeeEnabledChannelsOrBuilderList();
  /**
   * <pre>
   * list of fee enabled channels
   * </pre>
   *
   * <code>repeated .ibc.applications.fee.v1.FeeEnabledChannel fee_enabled_channels = 1 [json_name = "feeEnabledChannels", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"fee_enabled_channels&#92;""];</code>
   */
  com.ibc.applications.fee.v1.FeeEnabledChannelOrBuilder getFeeEnabledChannelsOrBuilder(
      int index);
}
