// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orders/key/key.proto

package com.assetmantle.modules.orders.key;

public final class KeyProto {
  private KeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_orders_key_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_orders_key_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024orders/key/key.proto\022\036assetmantle.modu" +
      "les.orders.key\032\027ids/base/order_id.proto\"" +
      "G\n\003Key\022@\n\torder_i_d\030\001 \001(\0132$.assetmantle." +
      "schema.ids.base.OrderIDR\007orderIDB\367\001\n\"com" +
      ".assetmantle.modules.orders.keyB\010KeyProt" +
      "oP\001Z+github.com/AssetMantle/modules/x/or" +
      "ders/key\242\002\004AMOK\252\002\036Assetmantle.Modules.Or" +
      "ders.Key\312\002\036Assetmantle\\Modules\\Orders\\Ke" +
      "y\342\002*Assetmantle\\Modules\\Orders\\Key\\GPBMe" +
      "tadata\352\002!Assetmantle::Modules::Orders::K" +
      "eyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.schema.ids.base.OrderIdProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_orders_key_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_orders_key_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_orders_key_Key_descriptor,
        new java.lang.String[] { "OrderID", });
    com.assetmantle.schema.ids.base.OrderIdProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
