// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/base/linked_data.proto

package com.assetmantle.schema.data.base;

public final class LinkedDataProto {
  private LinkedDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_schema_data_base_LinkedData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_schema_data_base_LinkedData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033data/base/linked_data.proto\022\034assetmant" +
      "le.schema.data.base\032\024gogoproto/gogo.prot" +
      "o\032\026ids/base/hash_id.proto\032\030ids/base/stri" +
      "ng_id.proto\"\317\001\n\nLinkedData\022E\n\014resource_i" +
      "_d\030\001 \001(\0132#.assetmantle.schema.ids.base.H" +
      "ashIDR\nresourceID\022I\n\rextension_i_d\030\002 \001(\013" +
      "2%.assetmantle.schema.ids.base.StringIDR" +
      "\013extensionID\022)\n\020service_endpoint\030\003 \001(\tR\017" +
      "serviceEndpoint:\004\210\240\037\000B\363\001\n com.assetmantl" +
      "e.schema.data.baseB\017LinkedDataProtoP\001Z*g" +
      "ithub.com/AssetMantle/schema/go/data/bas" +
      "e\242\002\004ASDB\252\002\034Assetmantle.Schema.Data.Base\312" +
      "\002\034Assetmantle\\Schema\\Data\\Base\342\002(Assetma" +
      "ntle\\Schema\\Data\\Base\\GPBMetadata\352\002\037Asse" +
      "tmantle::Schema::Data::Baseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.assetmantle.schema.ids.base.HashIdProto.getDescriptor(),
          com.assetmantle.schema.ids.base.StringIdProto.getDescriptor(),
        });
    internal_static_assetmantle_schema_data_base_LinkedData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_schema_data_base_LinkedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_schema_data_base_LinkedData_descriptor,
        new java.lang.String[] { "ResourceID", "ExtensionID", "ServiceEndpoint", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.assetmantle.schema.ids.base.HashIdProto.getDescriptor();
    com.assetmantle.schema.ids.base.StringIdProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
