// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/transactions/deputize/message.proto

package com.assetmantle.modules.assets.transactions.deputize;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_assets_transactions_deputize_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_assets_transactions_deputize_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*assets/transactions/deputize/message.p" +
      "roto\0220assetmantle.modules.assets.transac" +
      "tions.deputize\032 ids/base/classification_" +
      "id.proto\032\032ids/base/identity_id.proto\032\036li" +
      "sts/base/property_list.proto\"\362\004\n\007Message" +
      "\022\022\n\004from\030\001 \001(\tR\004from\022A\n\010from_i_d\030\002 \001(\0132\'" +
      ".assetmantle.schema.ids.base.IdentityIDR" +
      "\006fromID\022=\n\006to_i_d\030\003 \001(\0132\'.assetmantle.sc" +
      "hema.ids.base.IdentityIDR\004toID\022[\n\022classi" +
      "fication_i_d\030\004 \001(\0132-.assetmantle.schema." +
      "ids.base.ClassificationIDR\020classificatio" +
      "nID\022`\n\025maintained_properties\030\005 \001(\0132+.ass" +
      "etmantle.schema.lists.base.PropertyListR" +
      "\024maintainedProperties\022$\n\016can_mint_asset\030" +
      "\006 \001(\010R\014canMintAsset\0220\n\024can_renumerate_as" +
      "set\030\007 \001(\010R\022canRenumerateAsset\022$\n\016can_bur" +
      "n_asset\030\010 \001(\010R\014canBurnAsset\022,\n\022can_add_m" +
      "aintainer\030\t \001(\010R\020canAddMaintainer\0222\n\025can" +
      "_remove_maintainer\030\n \001(\010R\023canRemoveMaint" +
      "ainer\0222\n\025can_mutate_maintainer\030\013 \001(\010R\023ca" +
      "nMutateMaintainerB\351\002\n4com.assetmantle.mo" +
      "dules.assets.transactions.deputizeB\014Mess" +
      "ageProtoP\001Z=github.com/AssetMantle/modul" +
      "es/x/assets/transactions/deputize\242\002\005AMAT" +
      "D\252\0020Assetmantle.Modules.Assets.Transacti" +
      "ons.Deputize\312\0020Assetmantle\\Modules\\Asset" +
      "s\\Transactions\\Deputize\342\002<Assetmantle\\Mo" +
      "dules\\Assets\\Transactions\\Deputize\\GPBMe" +
      "tadata\352\0024Assetmantle::Modules::Assets::T" +
      "ransactions::Deputizeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.schema.ids.base.ClassificationIdProto.getDescriptor(),
          com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor(),
          com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_assets_transactions_deputize_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_assets_transactions_deputize_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_assets_transactions_deputize_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ToID", "ClassificationID", "MaintainedProperties", "CanMintAsset", "CanRenumerateAsset", "CanBurnAsset", "CanAddMaintainer", "CanRemoveMaintainer", "CanMutateMaintainer", });
    com.assetmantle.schema.ids.base.ClassificationIdProto.getDescriptor();
    com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor();
    com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
