// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/applications/interchain_accounts/controller/v1/controller.proto

package com.ibc.applications.interchain_accounts.controller.v1;

public final class ControllerProto {
  private ControllerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ibc_applications_interchain_accounts_controller_v1_Params_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ibc_applications_interchain_accounts_controller_v1_Params_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCibc/applications/interchain_accounts/c" +
      "ontroller/v1/controller.proto\0222ibc.appli" +
      "cations.interchain_accounts.controller.v" +
      "1\032\024gogoproto/gogo.proto\"V\n\006Params\022L\n\022con" +
      "troller_enabled\030\001 \001(\010B\035\362\336\037\031yaml:\"control" +
      "ler_enabled\"R\021controllerEnabledB\204\003\n6com." +
      "ibc.applications.interchain_accounts.con" +
      "troller.v1B\017ControllerProtoP\001ZPgithub.co" +
      "m/cosmos/ibc-go/v4/modules/apps/27-inter" +
      "chain-accounts/controller/types\242\002\004IAIC\252\002" +
      "1Ibc.Applications.InterchainAccounts.Con" +
      "troller.V1\312\0021Ibc\\Applications\\Interchain" +
      "Accounts\\Controller\\V1\342\002=Ibc\\Application" +
      "s\\InterchainAccounts\\Controller\\V1\\GPBMe" +
      "tadata\352\0025Ibc::Applications::InterchainAc" +
      "counts::Controller::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_ibc_applications_interchain_accounts_controller_v1_Params_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ibc_applications_interchain_accounts_controller_v1_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ibc_applications_interchain_accounts_controller_v1_Params_descriptor,
        new java.lang.String[] { "ControllerEnabled", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.moretags);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
