// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/applications/interchain_accounts/controller/v1/controller.proto

package com.ibc.applications.interchain_accounts.controller.v1;

public interface ParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibc.applications.interchain_accounts.controller.v1.Params)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * controller_enabled enables or disables the controller submodule.
   * </pre>
   *
   * <code>bool controller_enabled = 1 [json_name = "controllerEnabled", (.gogoproto.moretags) = "yaml:&#92;"controller_enabled&#92;""];</code>
   * @return The controllerEnabled.
   */
  boolean getControllerEnabled();
}
