// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maintainers/queries/maintainers/query_request.proto

package com.assetmantle.modules.maintainers.queries.maintainers;

public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assetmantle.modules.maintainers.queries.maintainers.QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.assetmantle.modules.maintainers.key.Key key = 1 [json_name = "key"];</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>.assetmantle.modules.maintainers.key.Key key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.assetmantle.modules.maintainers.key.Key getKey();
  /**
   * <code>.assetmantle.modules.maintainers.key.Key key = 1 [json_name = "key"];</code>
   */
  com.assetmantle.modules.maintainers.key.KeyOrBuilder getKeyOrBuilder();

  /**
   * <code>int32 limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();
}
