// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/privval/types.proto

package com.tendermint.privval;

public interface SignVoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tendermint.privval.SignVoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tendermint.types.Vote vote = 1 [json_name = "vote"];</code>
   * @return Whether the vote field is set.
   */
  boolean hasVote();
  /**
   * <code>.tendermint.types.Vote vote = 1 [json_name = "vote"];</code>
   * @return The vote.
   */
  com.tendermint.types.Vote getVote();
  /**
   * <code>.tendermint.types.Vote vote = 1 [json_name = "vote"];</code>
   */
  com.tendermint.types.VoteOrBuilder getVoteOrBuilder();

  /**
   * <code>string chain_id = 2 [json_name = "chainId"];</code>
   * @return The chainId.
   */
  java.lang.String getChainId();
  /**
   * <code>string chain_id = 2 [json_name = "chainId"];</code>
   * @return The bytes for chainId.
   */
  com.google.protobuf.ByteString
      getChainIdBytes();
}
