package constants

object Actor {

  val PRIMARY_ACTOR_SYSTEM = "PRIMARY_ACTOR_SYSTEM"
  val ACTOR_PUSH_NOTIFICATION = "ACTOR_PUSH_NOTIFICATION"

  val ACTOR_NOT_FOUND = "ACTOR_NOT_FOUND"

  val ACTOR_APP_WEB_SOCKET = "ACTOR_APP_WEB_SOCKET"
  val UNKNOWN_MESSAGE_TYPE = "UNKNOWN_MESSAGE_TYPE"

  object MessageType {
    val PING = "PING"
    val PONG = "PONG"
    val PUBLIC_MESSAGE = "PUBLIC_MESSAGE"
    val CHAT = "CHAT"
    val ASSET = "ASSET"
    val NOTIFICATION = "NOTIFICATION"
    val TEST = "TEST"
  }

}
