package constants

object Session {
  val USERNAME = "USERNAME"
  val TOKEN = "TOKEN"
  val ADDRESS = "ADDRESS"
  val TOKEN_TIME = "TOKEN_TIME"
  val NOT_LOGGED_IN = "NOT_LOGGED_IN"
  val INVALID_LOG_IN = "INVALID_LOG_IN"
  val FORWARDED_IP_ADDRESS_HEADER = "x-original-forwarded-for"

  object Log {

    val CONTROLLERS_REQUEST = "CONTROLLERS_REQUEST"
    val CONTROLLERS_RESPONSE = "CONTROLLERS_RESPONSE"
    val STORE_FILE_ENTRY = "STORE_FILE_ENTRY"
    val STORE_FILE_EXIT = "STORE_FILE_EXIT"

  }
}
