// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metas/queries/metas/query_request.proto

package com.assetmantle.modules.metas.queries.metas;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_metas_queries_metas_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_metas_queries_metas_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'metas/queries/metas/query_request.prot" +
      "o\022\'assetmantle.modules.metas.queries.met" +
      "as\032\023metas/key/key.proto\"Z\n\014QueryRequest\022" +
      "4\n\003key\030\001 \001(\0132\".assetmantle.modules.metas" +
      ".key.KeyR\003key\022\024\n\005limit\030\002 \001(\005R\005limitB\270\002\n+" +
      "com.assetmantle.modules.metas.queries.me" +
      "tasB\021QueryRequestProtoP\001Z4github.com/Ass" +
      "etMantle/modules/x/metas/queries/metas\242\002" +
      "\005AMMQM\252\002\'Assetmantle.Modules.Metas.Queri" +
      "es.Metas\312\002\'Assetmantle\\Modules\\Metas\\Que" +
      "ries\\Metas\342\0023Assetmantle\\Modules\\Metas\\Q" +
      "ueries\\Metas\\GPBMetadata\352\002+Assetmantle::" +
      "Modules::Metas::Queries::Metasb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.modules.metas.key.KeyProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_metas_queries_metas_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_metas_queries_metas_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_metas_queries_metas_QueryRequest_descriptor,
        new java.lang.String[] { "Key", "Limit", });
    com.assetmantle.modules.metas.key.KeyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
