// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maintainers/queries/maintainer/query_request.proto

package com.assetmantle.modules.maintainers.queries.maintainer;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_maintainers_queries_maintainer_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_maintainers_queries_maintainer_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2maintainers/queries/maintainer/query_r" +
      "equest.proto\0222assetmantle.modules.mainta" +
      "iners.queries.maintainer\032\031maintainers/ke" +
      "y/key.proto\"J\n\014QueryRequest\022:\n\003key\030\001 \001(\013" +
      "2(.assetmantle.modules.maintainers.key.K" +
      "eyR\003keyB\372\002\n6com.assetmantle.modules.main" +
      "tainers.queries.maintainerB\021QueryRequest" +
      "ProtoP\001Z?github.com/AssetMantle/modules/" +
      "x/maintainers/queries/maintainer\242\002\005AMMQM" +
      "\252\0022Assetmantle.Modules.Maintainers.Queri" +
      "es.Maintainer\312\0022Assetmantle\\Modules\\Main" +
      "tainers\\Queries\\Maintainer\342\002>Assetmantle" +
      "\\Modules\\Maintainers\\Queries\\Maintainer\\" +
      "GPBMetadata\352\0026Assetmantle::Modules::Main" +
      "tainers::Queries::Maintainerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.modules.maintainers.key.KeyProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_maintainers_queries_maintainer_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_maintainers_queries_maintainer_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_maintainers_queries_maintainer_QueryRequest_descriptor,
        new java.lang.String[] { "Key", });
    com.assetmantle.modules.maintainers.key.KeyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
