// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/capability/v1beta1/capability.proto

package com.cosmos.capability.v1beta1;

public interface OwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cosmos.capability.v1beta1.Owner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string module = 1 [json_name = "module", (.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
   * @return The module.
   */
  java.lang.String getModule();
  /**
   * <code>string module = 1 [json_name = "module", (.gogoproto.moretags) = "yaml:&#92;"module&#92;""];</code>
   * @return The bytes for module.
   */
  com.google.protobuf.ByteString
      getModuleBytes();

  /**
   * <code>string name = 2 [json_name = "name", (.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name", (.gogoproto.moretags) = "yaml:&#92;"name&#92;""];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
