// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/lightclients/solomachine/v1/solomachine.proto

package com.ibc.lightclients.solomachine.v1;

public interface PacketReceiptAbsenceDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ibc.lightclients.solomachine.v1.PacketReceiptAbsenceData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes path = 1 [json_name = "path"];</code>
   * @return The path.
   */
  com.google.protobuf.ByteString getPath();
}
