// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qualified/base/immutables.proto

package com.assetmantle.schema.qualified.base;

public final class ImmutablesProto {
  private ImmutablesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_schema_qualified_base_Immutables_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_schema_qualified_base_Immutables_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037qualified/base/immutables.proto\022!asset" +
      "mantle.schema.qualified.base\032\024gogoproto/" +
      "gogo.proto\032\036lists/base/property_list.pro" +
      "to\"d\n\nImmutables\022P\n\rproperty_list\030\001 \001(\0132" +
      "+.assetmantle.schema.lists.base.Property" +
      "ListR\014propertyList:\004\210\240\037\000B\221\002\n%com.assetma" +
      "ntle.schema.qualified.baseB\017ImmutablesPr" +
      "otoP\001Z/github.com/AssetMantle/schema/go/" +
      "qualified/base\242\002\004ASQB\252\002!Assetmantle.Sche" +
      "ma.Qualified.Base\312\002!Assetmantle\\Schema\\Q" +
      "ualified\\Base\342\002-Assetmantle\\Schema\\Quali" +
      "fied\\Base\\GPBMetadata\352\002$Assetmantle::Sch" +
      "ema::Qualified::Baseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor(),
        });
    internal_static_assetmantle_schema_qualified_base_Immutables_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_schema_qualified_base_Immutables_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_schema_qualified_base_Immutables_descriptor,
        new java.lang.String[] { "PropertyList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
