// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/transactions/burn/message.proto

package com.assetmantle.modules.assets.transactions.burn;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_assets_transactions_burn_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_assets_transactions_burn_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&assets/transactions/burn/message.proto" +
      "\022,assetmantle.modules.assets.transaction" +
      "s.burn\032\027ids/base/asset_id.proto\032\032ids/bas" +
      "e/identity_id.proto\"\242\001\n\007Message\022\022\n\004from\030" +
      "\001 \001(\tR\004from\022A\n\010from_i_d\030\002 \001(\0132\'.assetman" +
      "tle.schema.ids.base.IdentityIDR\006fromID\022@" +
      "\n\tasset_i_d\030\003 \001(\0132$.assetmantle.schema.i" +
      "ds.base.AssetIDR\007assetIDB\321\002\n0com.assetma" +
      "ntle.modules.assets.transactions.burnB\014M" +
      "essageProtoP\001Z9github.com/AssetMantle/mo" +
      "dules/x/assets/transactions/burn\242\002\005AMATB" +
      "\252\002,Assetmantle.Modules.Assets.Transactio" +
      "ns.Burn\312\002,Assetmantle\\Modules\\Assets\\Tra" +
      "nsactions\\Burn\342\0028Assetmantle\\Modules\\Ass" +
      "ets\\Transactions\\Burn\\GPBMetadata\352\0020Asse" +
      "tmantle::Modules::Assets::Transactions::" +
      "Burnb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.schema.ids.base.AssetIdProto.getDescriptor(),
          com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_assets_transactions_burn_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_assets_transactions_burn_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_assets_transactions_burn_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "AssetID", });
    com.assetmantle.schema.ids.base.AssetIdProto.getDescriptor();
    com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
