// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identities/transactions/name/message.proto

package com.assetmantle.modules.identities.transactions.name;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_identities_transactions_name_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_identities_transactions_name_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*identities/transactions/name/message.p" +
      "roto\0220assetmantle.modules.identities.tra" +
      "nsactions.name\032\030ids/base/string_id.proto" +
      "\"X\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\0229\n\004name\030" +
      "\002 \001(\0132%.assetmantle.schema.ids.base.Stri" +
      "ngIDR\004nameB\351\002\n4com.assetmantle.modules.i" +
      "dentities.transactions.nameB\014MessageProt" +
      "oP\001Z=github.com/AssetMantle/modules/x/id" +
      "entities/transactions/name\242\002\005AMITN\252\0020Ass" +
      "etmantle.Modules.Identities.Transactions" +
      ".Name\312\0020Assetmantle\\Modules\\Identities\\T" +
      "ransactions\\Name\342\002<Assetmantle\\Modules\\I" +
      "dentities\\Transactions\\Name\\GPBMetadata\352" +
      "\0024Assetmantle::Modules::Identities::Tran" +
      "sactions::Nameb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.schema.ids.base.StringIdProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_identities_transactions_name_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_identities_transactions_name_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_identities_transactions_name_Message_descriptor,
        new java.lang.String[] { "From", "Name", });
    com.assetmantle.schema.ids.base.StringIdProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
