// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orders/queries/orders/query_request.proto

package com.assetmantle.modules.orders.queries.orders;

public final class QueryRequestProto {
  private QueryRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_orders_queries_orders_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_orders_queries_orders_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)orders/queries/orders/query_request.pr" +
      "oto\022)assetmantle.modules.orders.queries." +
      "orders\032\024orders/key/key.proto\"[\n\014QueryReq" +
      "uest\0225\n\003key\030\001 \001(\0132#.assetmantle.modules." +
      "orders.key.KeyR\003key\022\024\n\005limit\030\002 \001(\005R\005limi" +
      "tB\304\002\n-com.assetmantle.modules.orders.que" +
      "ries.ordersB\021QueryRequestProtoP\001Z6github" +
      ".com/AssetMantle/modules/x/orders/querie" +
      "s/orders\242\002\005AMOQO\252\002)Assetmantle.Modules.O" +
      "rders.Queries.Orders\312\002)Assetmantle\\Modul" +
      "es\\Orders\\Queries\\Orders\342\0025Assetmantle\\M" +
      "odules\\Orders\\Queries\\Orders\\GPBMetadata" +
      "\352\002-Assetmantle::Modules::Orders::Queries" +
      "::Ordersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.modules.orders.key.KeyProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_orders_queries_orders_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_orders_queries_orders_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_orders_queries_orders_QueryRequest_descriptor,
        new java.lang.String[] { "Key", "Limit", });
    com.assetmantle.modules.orders.key.KeyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
