// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/tx/v1beta1/service.proto

package com.cosmos.tx.v1beta1;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_GetTxsEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_GetTxsEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_BroadcastTxRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_BroadcastTxRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_BroadcastTxResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_BroadcastTxResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_SimulateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_SimulateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_SimulateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_SimulateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_GetTxRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_GetTxRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_GetTxResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_GetTxResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_GetBlockWithTxsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_GetBlockWithTxsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_tx_v1beta1_GetBlockWithTxsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_tx_v1beta1_GetBlockWithTxsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037cosmos/tx/v1beta1/service.proto\022\021cosmo" +
      "s.tx.v1beta1\032\034google/api/annotations.pro" +
      "to\032#cosmos/base/abci/v1beta1/abci.proto\032" +
      "\032cosmos/tx/v1beta1/tx.proto\032\024gogoproto/g" +
      "ogo.proto\032*cosmos/base/query/v1beta1/pag" +
      "ination.proto\032\034tendermint/types/block.pr" +
      "oto\032\034tendermint/types/types.proto\"\253\001\n\022Ge" +
      "tTxsEventRequest\022\026\n\006events\030\001 \003(\tR\006events" +
      "\022F\n\npagination\030\002 \001(\0132&.cosmos.base.query" +
      ".v1beta1.PageRequestR\npagination\0225\n\010orde" +
      "r_by\030\003 \001(\0162\032.cosmos.tx.v1beta1.OrderByR\007" +
      "orderBy\"\320\001\n\023GetTxsEventResponse\022\'\n\003txs\030\001" +
      " \003(\0132\025.cosmos.tx.v1beta1.TxR\003txs\022G\n\014tx_r" +
      "esponses\030\002 \003(\0132$.cosmos.base.abci.v1beta" +
      "1.TxResponseR\013txResponses\022G\n\npagination\030" +
      "\003 \001(\0132\'.cosmos.base.query.v1beta1.PageRe" +
      "sponseR\npagination\"e\n\022BroadcastTxRequest" +
      "\022\031\n\010tx_bytes\030\001 \001(\014R\007txBytes\0224\n\004mode\030\002 \001(" +
      "\0162 .cosmos.tx.v1beta1.BroadcastModeR\004mod" +
      "e\"\\\n\023BroadcastTxResponse\022E\n\013tx_response\030" +
      "\001 \001(\0132$.cosmos.base.abci.v1beta1.TxRespo" +
      "nseR\ntxResponse\"W\n\017SimulateRequest\022)\n\002tx" +
      "\030\001 \001(\0132\025.cosmos.tx.v1beta1.TxB\002\030\001R\002tx\022\031\n" +
      "\010tx_bytes\030\002 \001(\014R\007txBytes\"\212\001\n\020SimulateRes" +
      "ponse\022<\n\010gas_info\030\001 \001(\0132!.cosmos.base.ab" +
      "ci.v1beta1.GasInfoR\007gasInfo\0228\n\006result\030\002 " +
      "\001(\0132 .cosmos.base.abci.v1beta1.ResultR\006r" +
      "esult\"\"\n\014GetTxRequest\022\022\n\004hash\030\001 \001(\tR\004has" +
      "h\"}\n\rGetTxResponse\022%\n\002tx\030\001 \001(\0132\025.cosmos." +
      "tx.v1beta1.TxR\002tx\022E\n\013tx_response\030\002 \001(\0132$" +
      ".cosmos.base.abci.v1beta1.TxResponseR\ntx" +
      "Response\"x\n\026GetBlockWithTxsRequest\022\026\n\006he" +
      "ight\030\001 \001(\003R\006height\022F\n\npagination\030\002 \001(\0132&" +
      ".cosmos.base.query.v1beta1.PageRequestR\n" +
      "pagination\"\360\001\n\027GetBlockWithTxsResponse\022\'" +
      "\n\003txs\030\001 \003(\0132\025.cosmos.tx.v1beta1.TxR\003txs\022" +
      "4\n\010block_id\030\002 \001(\0132\031.tendermint.types.Blo" +
      "ckIDR\007blockId\022-\n\005block\030\003 \001(\0132\027.tendermin" +
      "t.types.BlockR\005block\022G\n\npagination\030\004 \001(\013" +
      "2\'.cosmos.base.query.v1beta1.PageRespons" +
      "eR\npagination*H\n\007OrderBy\022\030\n\024ORDER_BY_UNS" +
      "PECIFIED\020\000\022\020\n\014ORDER_BY_ASC\020\001\022\021\n\rORDER_BY" +
      "_DESC\020\002*|\n\rBroadcastMode\022\036\n\032BROADCAST_MO" +
      "DE_UNSPECIFIED\020\000\022\030\n\024BROADCAST_MODE_BLOCK" +
      "\020\001\022\027\n\023BROADCAST_MODE_SYNC\020\002\022\030\n\024BROADCAST" +
      "_MODE_ASYNC\020\0032\222\005\n\007Service\022{\n\010Simulate\022\"." +
      "cosmos.tx.v1beta1.SimulateRequest\032#.cosm" +
      "os.tx.v1beta1.SimulateResponse\"&\202\323\344\223\002 :\001" +
      "*\"\033/cosmos/tx/v1beta1/simulate\022q\n\005GetTx\022" +
      "\037.cosmos.tx.v1beta1.GetTxRequest\032 .cosmo" +
      "s.tx.v1beta1.GetTxResponse\"%\202\323\344\223\002\037\022\035/cos" +
      "mos/tx/v1beta1/txs/{hash}\022\177\n\013BroadcastTx" +
      "\022%.cosmos.tx.v1beta1.BroadcastTxRequest\032" +
      "&.cosmos.tx.v1beta1.BroadcastTxResponse\"" +
      "!\202\323\344\223\002\033:\001*\"\026/cosmos/tx/v1beta1/txs\022|\n\013Ge" +
      "tTxsEvent\022%.cosmos.tx.v1beta1.GetTxsEven" +
      "tRequest\032&.cosmos.tx.v1beta1.GetTxsEvent" +
      "Response\"\036\202\323\344\223\002\030\022\026/cosmos/tx/v1beta1/txs" +
      "\022\227\001\n\017GetBlockWithTxs\022).cosmos.tx.v1beta1" +
      ".GetBlockWithTxsRequest\032*.cosmos.tx.v1be" +
      "ta1.GetBlockWithTxsResponse\"-\202\323\344\223\002\'\022%/co" +
      "smos/tx/v1beta1/txs/block/{height}B\266\001\n\025c" +
      "om.cosmos.tx.v1beta1B\014ServiceProtoP\001Z%gi" +
      "thub.com/cosmos/cosmos-sdk/types/tx\242\002\003CT" +
      "X\252\002\021Cosmos.Tx.V1beta1\312\002\021Cosmos\\Tx\\V1beta" +
      "1\342\002\035Cosmos\\Tx\\V1beta1\\GPBMetadata\352\002\023Cosm" +
      "os::Tx::V1beta1\300\343\036\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.cosmos.base.abci.v1beta1.AbciProto.getDescriptor(),
          com.cosmos.tx.v1beta1.TxProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
          com.cosmos.base.query.v1beta1.PaginationProto.getDescriptor(),
          com.tendermint.types.BlockProto.getDescriptor(),
          com.tendermint.types.TypesProto.getDescriptor(),
        });
    internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_GetTxsEventRequest_descriptor,
        new java.lang.String[] { "Events", "Pagination", "OrderBy", });
    internal_static_cosmos_tx_v1beta1_GetTxsEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_tx_v1beta1_GetTxsEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_GetTxsEventResponse_descriptor,
        new java.lang.String[] { "Txs", "TxResponses", "Pagination", });
    internal_static_cosmos_tx_v1beta1_BroadcastTxRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cosmos_tx_v1beta1_BroadcastTxRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_BroadcastTxRequest_descriptor,
        new java.lang.String[] { "TxBytes", "Mode", });
    internal_static_cosmos_tx_v1beta1_BroadcastTxResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cosmos_tx_v1beta1_BroadcastTxResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_BroadcastTxResponse_descriptor,
        new java.lang.String[] { "TxResponse", });
    internal_static_cosmos_tx_v1beta1_SimulateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cosmos_tx_v1beta1_SimulateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_SimulateRequest_descriptor,
        new java.lang.String[] { "Tx", "TxBytes", });
    internal_static_cosmos_tx_v1beta1_SimulateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cosmos_tx_v1beta1_SimulateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_SimulateResponse_descriptor,
        new java.lang.String[] { "GasInfo", "Result", });
    internal_static_cosmos_tx_v1beta1_GetTxRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cosmos_tx_v1beta1_GetTxRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_GetTxRequest_descriptor,
        new java.lang.String[] { "Hash", });
    internal_static_cosmos_tx_v1beta1_GetTxResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cosmos_tx_v1beta1_GetTxResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_GetTxResponse_descriptor,
        new java.lang.String[] { "Tx", "TxResponse", });
    internal_static_cosmos_tx_v1beta1_GetBlockWithTxsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_cosmos_tx_v1beta1_GetBlockWithTxsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_GetBlockWithTxsRequest_descriptor,
        new java.lang.String[] { "Height", "Pagination", });
    internal_static_cosmos_tx_v1beta1_GetBlockWithTxsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_cosmos_tx_v1beta1_GetBlockWithTxsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_tx_v1beta1_GetBlockWithTxsResponse_descriptor,
        new java.lang.String[] { "Txs", "BlockId", "Block", "Pagination", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoRegistration);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.cosmos.base.abci.v1beta1.AbciProto.getDescriptor();
    com.cosmos.tx.v1beta1.TxProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
    com.cosmos.base.query.v1beta1.PaginationProto.getDescriptor();
    com.tendermint.types.BlockProto.getDescriptor();
    com.tendermint.types.TypesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
