// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maintainers/record/record.proto

package com.assetmantle.modules.maintainers.record;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assetmantle.modules.maintainers.record.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.assetmantle.modules.maintainers.key.Key key = 1 [json_name = "key"];</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>.assetmantle.modules.maintainers.key.Key key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  com.assetmantle.modules.maintainers.key.Key getKey();
  /**
   * <code>.assetmantle.modules.maintainers.key.Key key = 1 [json_name = "key"];</code>
   */
  com.assetmantle.modules.maintainers.key.KeyOrBuilder getKeyOrBuilder();

  /**
   * <code>.assetmantle.modules.maintainers.mappable.Mappable mappable = 2 [json_name = "mappable"];</code>
   * @return Whether the mappable field is set.
   */
  boolean hasMappable();
  /**
   * <code>.assetmantle.modules.maintainers.mappable.Mappable mappable = 2 [json_name = "mappable"];</code>
   * @return The mappable.
   */
  com.assetmantle.modules.maintainers.mappable.Mappable getMappable();
  /**
   * <code>.assetmantle.modules.maintainers.mappable.Mappable mappable = 2 [json_name = "mappable"];</code>
   */
  com.assetmantle.modules.maintainers.mappable.MappableOrBuilder getMappableOrBuilder();
}
